quarkus.application.name=event-gateway
quarkus.http.host=0.0.0.0
quarkus.http.port=8081

camel.main.startup-summary-level=verbose

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.eventmanagement.gateway".level=INFO

# Apache Kafka
event.gateway.kafka.brokers=localhost:9092
event.gateway.kafka.topic=events.raw

# Productor Kafka
camel.component.kafka.brokers=${event.gateway.kafka.brokers}
