import {navigation} from "../../navigation/navigation.registry";
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {readPlatform,states,type Snapshot} from '../administration/platform';
import './home.css';
const plugins=[['Tickets','ServiceNow · Ticketing','/ticketing/tickets'],['Notifications','GNM · Notifications','/notifications'],['CACF','CACF · Automations','/cacf']];
const system=navigation.find(g=>g.label==='Sistema')!.items.map(i=>[i.label,i.description,i.path]);
const platform=navigation.find(g=>g.label==='Plataforma')!.items.filter(i=>i.path!=='/dashboard'&&i.status==='active').map(i=>[i.label,i.path]);
export function HomePage(){
 const {t,locale}=useI18n();const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const abort=new AbortController();let active=true;setLoading(true);setError('');setSnapshot(null);const timeout=setTimeout(()=>abort.abort(),8000);readPlatform(abort.signal).then(d=>{if(active)setSnapshot(d);}).catch(e=>{if(active)setError(abort.signal.aborted?'La API no respondió en 8 segundos. Puedes volver a intentar.':e instanceof Error?e.message:'No fue posible consultar la plataforma.');}).finally(()=>{clearTimeout(timeout);if(active)setLoading(false);});return()=>{active=false;abort.abort();clearTimeout(timeout);};},[revision]);
 useEffect(()=>{const interval=setInterval(()=>setRevision(v=>v+1),30000);return()=>clearInterval(interval);},[]);
 const services=snapshot?.services??[];const attention=services.filter(s=>['error','degraded','stopped'].includes(s.status)).length;
 return <section className="page home-dashboard"><div className="page-heading"><div><span className="eyebrow">OPEN EVENT MANAGEMENT</span><h1>{t('Dashboard general')}</h1><p>{t('Plano global de operación y administración de la plataforma.')}</p></div><button disabled={loading} onClick={()=>setRevision(v=>v+1)}>{t(loading?'Consultando…':'↻ Actualizar')}</button></div>
 <section aria-labelledby="home-plugins"><div className="section-heading"><h2 id="home-plugins">1. {t('Plugins')}</h2></div><div className="hero-grid">{plugins.map(([name,description,path])=><Link className="hero-card home-link" key={path} to={path}><small>{t('Plugin')}</small><strong>{name} <span aria-hidden="true">↗</span></strong><p>{name==='Tickets'?<>ServiceNow - Ticketing<br/>GLPI - Ticketing</>:description}</p></Link>)}</div></section>
 <section aria-labelledby="home-architecture"><div className="section-heading"><div><span className="eyebrow">{t('Arquitectura actual')}</span><h2 id="home-architecture">2. {t('Arquitectura')}</h2><p>{t('Componentes de la solución')}</p></div><Link to="/administration">{t('Ver inventario completo')} ↗</Link></div><p>{t('Healthchecks del runtime; no equivalen a certificación funcional.')} {t('Actualización automática cada 30 segundos')}</p>
 <div aria-live="polite">{loading&&<p role="status">{t('Consultando…')}</p>}{error&&<div role="alert" className="home-error"><strong>{t('Sin telemetría')}</strong><p>{t(error)}</p></div>}{snapshot&&<p>{t('Consulta')}: {new Date(snapshot.observedAt).toLocaleString(locale)} · {services.length} {t('Servicios')} · {attention} {t('Requieren atención')} · {services.filter(s=>s.status==='unknown').length} {t('sin verificar')}</p>}</div>
 <div className="module-grid">{services.map(s=><Link className="module-card home-link" to={'/administration?service='+encodeURIComponent(s.id)} key={s.id} aria-label={`${s.name} · ${t(states[s.status])}`}><span className={`home-health ${s.status}`}/><div><strong>{s.name}</strong><small>{t(s.category)} · {t(states[s.status])}</small><small>{t('Versión')}: {s.version??'—'} · {s.runtime??s.reason??'—'}</small></div><span aria-hidden="true">↗</span></Link>)}</div>{snapshot&&!services.length&&<p>{t('La API devolvió un inventario vacío.')}</p>}</section>
 <div className="home-bottom"><section aria-labelledby="home-system"><div className="section-heading"><h2 id="home-system">3. {t('Sistema')}</h2></div><div className="home-access">{system.map(([name,description,path])=><Link className="module-card home-link" key={path} to={path}><div><strong>{t(name)}</strong><small>{t(description)}</small></div><span aria-hidden="true">↗</span></Link>)}</div></section><section aria-labelledby="home-platform"><div className="section-heading"><h2 id="home-platform">4. {t('Plataforma')}</h2></div><div className="home-access">{platform.map(([name,path])=><Link className="module-card home-link" key={path} to={path}><strong>{t(name)}</strong><span aria-hidden="true">↗</span></Link>)}</div></section></div></section>;
}
