import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {ApiError,errorText} from '../blackouts/blackouts.api';
import {aiopsApi,configurationResponse,validateConfiguration,type Configuration,type Mutation} from './aiops.api';
import {AiopsAssessment} from './AiopsAssessment';
import '../catalog/catalog.css';import '../blackouts/blackouts.css';import '../inventory/inventory.css';
const storage='console.aiops.uncertain';
function stored():Mutation|null{try{return JSON.parse(sessionStorage.getItem(storage)||'null');}catch{return null;}}
const empty=()=>({id:'',name:'',enabled:false});
export function AiopsError({error}:{error:unknown}){const {t}=useI18n();if(!error)return null;const message=error instanceof ApiError&&error.code==='AIOPS_PROVIDER_UNAVAILABLE'?'El proveedor mock no respondió correctamente. No hay una recomendación disponible.':error instanceof ApiError&&error.code==='AIOPS_DISABLED'?'La configuración está deshabilitada. Actualiza su estado antes de consultar.':error instanceof ApiError&&error.status===409?'Conflicto de revisión o ID existente, eliminado o deshabilitado. Consulta el estado actual.':errorText(error);return <div role="alert" className="catalog-error">{t(message)}{error instanceof ApiError&&<small>HTTP {error.status} · {error.code}</small>}</div>;}
export function AiopsPage(){
 const {t}=useI18n();const [pending,setPending]=useState(stored),[tenant,setTenant]=useState(()=>stored()?.tenant??''),[input,setInput]=useState(()=>stored()?.tenant??''),[selected,setSelected]=useState<string|null>(()=>stored()?.id??null),[form,setForm]=useState(()=>{const p=stored();return p?{id:p.id,name:p.body?.name??'',enabled:p.body?.enabled??false}:empty();}),[record,setRecord]=useState<Configuration|null>(null),[etag,setEtag]=useState('"0"'),[items,setItems]=useState<Configuration[]>([]),[cursors,setCursors]=useState(['']),[revision,setRevision]=useState(0),[catalog,setCatalog]=useState(false),[truncated,setTruncated]=useState(false),[listError,setListError]=useState<unknown>(),[error,setError]=useState<unknown>(),[loading,setLoading]=useState(false),[reading,setReading]=useState(false),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[conflict,setConflict]=useState(false),[confirmation,setConfirmation]=useState<Mutation|null>(null),[notice,setNotice]=useState(''),[reconciled,setReconciled]=useState<{record:Configuration|null;etag:string|null}|undefined>(),[reconciling,setReconciling]=useState(false);const lock=useRef(false);const cursor=cursors[cursors.length-1];const locked=busy||!!pending;
 function refresh(){setCursors(['']);setRevision(x=>x+1);}
 useEffect(()=>{const abort=new AbortController();setItems([]);setListError(undefined);setTruncated(false);if(!tenant){setLoading(false);return;}setLoading(true);(async()=>{try{let rows:unknown[];if(catalog){const response=await fetch('/api/catalog/views/aiops-extensions',{signal:abort.signal,cache:'no-store',headers:{'X-Tenant-Id':tenant,'X-Actor-Id':'local-console'}});if(!response.ok)throw new ApiError(response.status,'CATALOG_UNAVAILABLE');const data=await response.json();if(!Array.isArray(data.items))throw new ApiError(503,'INVALID_RESPONSE');rows=data.items.filter((r:{tenant:string})=>r.tenant===tenant);if(!abort.signal.aborted)setTruncated(data.truncated===true);}else{const {data}=await aiopsApi<unknown>(tenant,'/aiops?limit=50&after='+encodeURIComponent(cursor),{signal:abort.signal});if(!Array.isArray(data))throw new ApiError(503,'INVALID_RESPONSE');rows=data;}const checked=rows.map(configurationResponse);if(!abort.signal.aborted)setItems(checked);}catch(e){if(!abort.signal.aborted)setListError(e);}finally{if(!abort.signal.aborted)setLoading(false);}})();return()=>abort.abort();},[tenant,cursor,revision,catalog]);
 useEffect(()=>{setRecord(null);setReading(false);setError(undefined);if(selected===null)return;if(selected===''){setForm(empty());setEtag('"0"');return;}if(pending)return;const abort=new AbortController();setReading(true);setForm({id:selected,name:'',enabled:false});aiopsApi<unknown>(tenant,'/aiops/'+encodeURIComponent(selected),{signal:abort.signal}).then(({data,etag})=>{if(abort.signal.aborted)return;const c=configurationResponse(data);if(!etag)throw new ApiError(503,'ETAG_MISSING');setRecord(c);setForm(c);setEtag(etag);}).catch(e=>{if(!abort.signal.aborted)setError(e);}).finally(()=>{if(!abort.signal.aborted)setReading(false);});return()=>abort.abort();},[selected,tenant]);
 function prepare(remove=false){setError(undefined);try{if(conflict||pending||reading)return;const c=remove&&record?record:validateConfiguration(form);const method=remove?'DELETE':record?'PUT':'POST';if(selected&& !record)throw new Error('Consulta la configuración antes de modificarla.');setConfirmation({tenant,id:c.id,method,path:method==='POST'?'/aiops':'/aiops/'+encodeURIComponent(c.id),etag:record?etag:'"0"',...(remove?{}:{body:method==='POST'?c:{name:c.name,enabled:c.enabled}})});}catch(e){setError(e);}}
 async function execute(op:Mutation){if(lock.current)return;lock.current=true;setBusy(true);setError(undefined);setNotice('');setReconciled(undefined);try{sessionStorage.setItem(storage,JSON.stringify(op));setPending(op);const response=await aiopsApi<unknown>(op.tenant,op.path,{method:op.method,body:op.body,etag:op.etag});if(op.method==='DELETE'){setRecord(null);setSelected(null);setForm(empty());setNotice('Baja lógica confirmada. El ID no puede reutilizarse.');}else{const c=configurationResponse(response.data);if(!response.etag)throw new ApiError(503,'ETAG_MISSING');setRecord(c);setForm(c);setSelected(c.id);setEtag(response.etag);setNotice('Configuración guardada. La consulta al mock es una acción separada.');}sessionStorage.removeItem(storage);setPending(null);setConflict(false);refresh();}catch(e){setError(e);if(e instanceof ApiError&&[400,404,409,413,422,428].includes(e.status)){sessionStorage.removeItem(storage);setPending(null);if(e.status===409)setConflict(true);}}finally{lock.current=false;setBusy(false);}}
 async function reconcile(){if(reconciling)return;setReconciling(true);setError(undefined);setReconciled(undefined);try{const id=pending?.id??form.id;const {data,etag}=await aiopsApi<unknown>(tenant,'/aiops/'+encodeURIComponent(id));const c=configurationResponse(data);if(!etag)throw new ApiError(503,'ETAG_MISSING');setReconciled({record:c,etag});}catch(e){if(e instanceof ApiError&&e.status===404)setReconciled({record:null,etag:null});else setError(e);}finally{setReconciling(false);}}
 function acceptRead(){if(!reconciled)return;const c=reconciled.record;sessionStorage.removeItem(storage);setPending(null);setConflict(false);setConfirmation(null);setRecord(c);setSelected(c?.id??null);setForm(c??empty());setEtag(reconciled.etag??'"0"');setReconciled(undefined);setNotice(c?'Estado reconciliado con la lectura actual. No se repitió ninguna escritura.':'La lectura confirma que el registro no está disponible. No se repitió ninguna escritura.');refresh();}
 const formLocked=locked||reading||!!confirmation;
 return <section className="page catalog-page blackout-page"><div className="page-heading"><div><span className="eyebrow">AIOps · INTERNAL_MOCK</span><h1>AIOps Extensions</h1><p>{t('Configuraciones independientes y consulta manual sintética.')}</p></div><button disabled={!tenant||loading||locked} onClick={refresh}>{t('Actualizar tabla')}</button></div><p>{t('Guardar enabled habilita consultas manuales directamente; no activa procesamiento automático de eventos.')}</p>
 <div className="catalog-toolbar"><label>Tenant<input aria-label="Tenant" value={input} disabled={locked} onChange={e=>setInput(e.target.value)}/></label><button disabled={locked} onClick={()=>{setTenant(input.trim());setSelected(null);setConflict(false);setReconciled(undefined);setNotice('');setError(undefined);setCursors(['']);}}>{t('Seleccionar tenant')}</button><input aria-label={t('Buscar en la tabla')} placeholder={t('Buscar en esta página')} value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={!tenant||locked||catalog} onClick={()=>{setSelected('');setForm(empty());setRecord(null);setEtag('"0"');setConflict(false);setError(undefined);setNotice('');setReconciled(undefined);}}>{t('Nueva configuración AIOps')}</button></div>
 <nav className="inventory-tabs" aria-label={t('Fuente de configuraciones AIOps')}><button aria-pressed={!catalog} disabled={locked} onClick={()=>{setCatalog(false);setCursors(['']);}}>{t('API AIOps por tenant')}</button><button aria-pressed={catalog} disabled={locked} onClick={()=>{setCatalog(true);setSelected(null);setCursors(['']);}}>{t('Catálogo · Solo consulta')}</button></nav><p>{tenant?`${t('Tenant seleccionado')}: ${tenant}`:t('Selecciona un tenant para consultar, escribir o simular.')}</p><AiopsError error={listError}/>{truncated&&<p role="status">{t('Se muestran los primeros 2000 registros. El catálogo está incompleto.')}</p>}
 <div className="catalog-table-wrap" aria-busy={loading}><table><thead><tr>{['ID','Nombre','Habilitado','Revisión','Detalle'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{items.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map(c=><tr key={c.id}><td>{c.id}</td><td>{c.name}</td><td>{t(c.enabled?'Sí':'No')}</td><td>{c.revision}</td><td>{!catalog&&<button disabled={locked} aria-label={`${t('Abrir AIOps')} ${c.id}`} onClick={()=>{setSelected(c.id);setConflict(false);setReconciled(undefined);setNotice('');}}>{t('Abrir')}</button>}</td></tr>)}</tbody></table>{loading?<p role="status">{t('Cargando…')}</p>:!items.length&&<p>{t('Sin registros')}</p>}</div>{!catalog&&tenant&&<div className="blackout-actions"><button disabled={loading||locked||cursors.length===1} onClick={()=>setCursors(a=>a.slice(0,-1))}>{t('Anterior')}</button><span>{t('Página')} {cursors.length} · {items.length}/50</span><button disabled={loading||locked||items.length<50} onClick={()=>setCursors(a=>[...a,items[items.length-1].id])}>{t('Siguiente')}</button></div>}
 <AiopsError error={error}/>{notice&&<p role="status" className="blackout-notice">{t(notice)}</p>}{(pending||conflict)&&<section className="blackout-notice" role="status"><p>{t(pending?'Respuesta incierta: consulta y reconcilia antes de escribir otra vez. No se reintentará automáticamente.':'Conflicto: el borrador se conserva. Consulta y compara el estado actual.')}</p>{pending&&<pre>{JSON.stringify({method:pending.method,id:pending.id,etag:pending.etag,body:pending.body},null,2)}</pre>}<button disabled={busy||reconciling} onClick={reconcile}>{t('Consultar estado para reconciliar')}</button>{reconciled!==undefined&&<><pre>{JSON.stringify(reconciled.record,null,2)}</pre><p>{t('Usar esta lectura reemplaza el borrador con el estado del servidor. Un 404 no permite saber si el ID fue dado de baja.')}</p><button disabled={busy} onClick={acceptRead}>{t('Usar estado actual del servidor')}</button></>}</section>}
 {!catalog&&tenant&&selected!==null&&<article className="blackout-editor"><h2>{t('Configuración AIOps')} · {record?.id||t('Nuevo')}</h2>{record&&<p>{t('Revisión')}: {record.revision} · ETag {etag} · enabled: {String(record.enabled)}</p>}<fieldset disabled={formLocked}><div className="blackout-fields"><label>ID<input aria-label="AIOps ID" disabled={!!selected} maxLength={64} value={form.id} onChange={e=>setForm({...form,id:e.target.value})}/></label><label>{t('Nombre')}<input maxLength={128} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label></div><label className="inventory-check"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>{t('Habilitar consulta manual')}</label><div className="blackout-actions"><button disabled={conflict||!!selected&&!record} onClick={()=>prepare()}>{t('Guardar configuración')}</button>{record&&<button disabled={conflict} onClick={()=>prepare(true)}>{t('Dar de baja')}</button>}</div></fieldset>{confirmation&&<section className="blackout-confirm" aria-label={t('Confirmar operación')}><h3>{t('Confirmar operación')}</h3><p>{confirmation.method} · {confirmation.id} · If-Match {confirmation.etag}</p><p>{t(confirmation.method==='DELETE'?'Baja lógica: conserva el ID y la auditoría. No podrá reutilizarse.':'Guardar cambia directamente la habilitación de consultas manuales.')}</p>{confirmation.body&&<pre>{JSON.stringify(confirmation.body,null,2)}</pre>}<button disabled={busy} onClick={()=>{const op=confirmation;setConfirmation(null);void execute(op);}}>{t('Confirmar envío')}</button><button disabled={busy} onClick={()=>setConfirmation(null)}>{t('Cancelar')}</button></section>}<p>{t('La auditoría de cambios existe en la base de datos, sin endpoint público de historial en este incremento.')}</p></article>}
 {!catalog&&record&&<AiopsAssessment key={tenant+':'+record.id} tenant={tenant} configuration={record}/>}
 </section>;
}
