import {ApiError} from '../blackouts/blackouts.api';
export type Configuration={id:string;name:string;enabled:boolean;revision:number};
export type Signal={resource:string;summary:string;severity:number};
export type Assessment={configurationId:string;revision:number;provider:'INTERNAL_MOCK';assessment:{recommendation:'OBSERVE'|'INVESTIGATE';confidence:number}};
export type Mutation={tenant:string;id:string;method:'POST'|'PUT'|'DELETE';path:string;body?:{id?:string;name:string;enabled:boolean};etag:string};
export async function aiopsApi<T>(tenant:string,path:string,options:{method?:string;body?:unknown;etag?:string;signal?:AbortSignal}={}):Promise<{data:T;etag:string|null}>{
 if(!tenant.trim())throw new Error('Selecciona un tenant.');const abort=new AbortController();const cancel=()=>abort.abort();options.signal?.addEventListener('abort',cancel);if(options.signal?.aborted)cancel();const timer=setTimeout(cancel,10000);
 try{const body=options.body===undefined?undefined:JSON.stringify(options.body);if(body&&body.length>8192)throw new ApiError(413,'REQUEST_SIZE_LIMIT');const response=await fetch('/api/processor/v1'+path,{method:options.method??'GET',cache:'no-store',signal:abort.signal,headers:{'Content-Type':'application/json','X-Tenant-Id':tenant,'X-Actor-Id':'local-console',...(options.etag?{'If-Match':options.etag}:{})},body});
 if(response.status===204)return {data:undefined as T,etag:response.headers.get('ETag')};let data;try{data=await response.json();}catch{throw new ApiError(response.ok?503:response.status,'INVALID_RESPONSE');}if(!response.ok)throw new ApiError(response.status,data.errorCode??data.code??'REQUEST_FAILED');return {data,etag:response.headers.get('ETag')};
 }catch(e){if(e instanceof ApiError||e instanceof Error&&e.message==='Selecciona un tenant.')throw e;throw new ApiError(503,'CONNECTION_UNCERTAIN');}finally{clearTimeout(timer);options.signal?.removeEventListener('abort',cancel);}
}
export function validateConfiguration(c:{id:string;name:string;enabled:boolean}){if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(c.id)||!c.name.trim()||c.name.length>128||typeof c.enabled!=='boolean')throw new Error('ID válido de hasta 64 caracteres y nombre no vacío de hasta 128; enabled debe ser booleano.');return c;}
export function validateSignal(s:Signal){if(!s.resource.trim()||s.resource.length>256||!s.summary.trim()||s.summary.length>1024||!Number.isInteger(s.severity)||s.severity<0||s.severity>5)throw new Error('Completa recurso y resumen; severidad debe ser un entero de 0 a 5.');return s;}
export function configurationResponse(value:unknown):Configuration{const c=value as Configuration;if(!c||typeof c.id!=='string'||typeof c.name!=='string'||typeof c.enabled!=='boolean'||!Number.isSafeInteger(c.revision)||c.revision<1)throw new ApiError(503,'INVALID_RESPONSE');return c;}
export function assessmentResponse(value:unknown):Assessment{const r=value as Assessment;if(!r||r.provider!=='INTERNAL_MOCK'||typeof r.configurationId!=='string'||!Number.isSafeInteger(r.revision)||r.revision<1||!r.assessment||!['OBSERVE','INVESTIGATE'].includes(r.assessment.recommendation)||typeof r.assessment.confidence!=='number'||!Number.isFinite(r.assessment.confidence)||r.assessment.confidence<0||r.assessment.confidence>1)throw new ApiError(503,'AIOPS_PROVIDER_UNAVAILABLE');return r;}
