import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {AiopsError} from './AiopsPage';
import {aiopsApi,assessmentResponse,validateSignal,type Assessment,type Configuration} from './aiops.api';
export function AiopsAssessment({tenant,configuration}:{tenant:string;configuration:Configuration}){
 const {t}=useI18n();const [resource,setResource]=useState(''),[summary,setSummary]=useState(''),[severity,setSeverity]=useState('2'),[busy,setBusy]=useState(false),[result,setResult]=useState<Assessment>(),[error,setError]=useState<unknown>();const request=useRef<AbortController>();useEffect(()=>()=>request.current?.abort(),[]);
 async function assess(){if(request.current)return;const abort=new AbortController();request.current=abort;setBusy(true);setError(undefined);setResult(undefined);try{if(!/^[0-5]$/.test(severity.trim()))throw new Error('Severidad numérica entera de 0 a 5, sin comillas.');const signal=validateSignal({resource,summary,severity:Number(severity.trim())});const {data}=await aiopsApi<unknown>(tenant,'/aiops/'+encodeURIComponent(configuration.id)+'/assessments',{method:'POST',body:signal,signal:abort.signal});const checked=assessmentResponse(data);if(checked.configurationId!==configuration.id)throw new Error('La respuesta no corresponde a esta configuración.');if(!abort.signal.aborted)setResult(checked);}catch(e){if(!abort.signal.aborted)setError(e);}finally{if(!abort.signal.aborted)setBusy(false);request.current=undefined;}}
 return <article className="blackout-editor"><h2>{t('Consulta manual al mock')}</h2><p className="blackout-notice">{t('Mock sintético INTERNAL_MOCK: sin inferencia real ni compatibilidad certificada con Kyndryl Bridge. No remedia, crea tickets ni participa automáticamente en el pipeline.')}</p><fieldset disabled={busy}><div className="blackout-fields"><label>{t('Recurso')}<input maxLength={256} value={resource} onChange={e=>setResource(e.target.value)}/></label><label>{t('Resumen')}<textarea maxLength={1024} value={summary} onChange={e=>setSummary(e.target.value)}/></label><label>{t('Severidad')}<input inputMode="numeric" value={severity} onChange={e=>setSeverity(e.target.value)}/></label></div>{configuration.enabled?<button onClick={assess}>{t(busy?'Consultando…':'Consultar mock')}</button>:<p>{t('Configuración deshabilitada: guarda enabled para habilitar la consulta manual.')}</p>}</fieldset><AiopsError error={error}/>{result&&<div role="status"><strong>INTERNAL_MOCK · {t('Resultado sintético')}</strong><p>configurationId: {result.configurationId} · {t('Revisión consultada')}: {result.revision}</p><p>recommendation: <strong>{result.assessment.recommendation}</strong> · confidence: {result.assessment.confidence}</p>{result.revision!==configuration.revision&&<p>{t('La configuración cambió después de iniciar esta consulta. Este resultado corresponde a la revisión indicada.')}</p>}</div>}<p>{t('Deshabilitar no cancela una consulta ya iniciada. Las señales y resultados no se guardan; no habrá historial de consultas tras recargar.')}</p></article>;
}
