import {useEffect,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import '../catalog/catalog.css';
import '../blackouts/blackouts.css';
type Secret={id:string;tenant:string;environment:string;name:string;kind:string;revision:number;enabled:boolean;updated_at:string};
export function SecretsPage(){const {t}=useI18n();const [tenant,setTenant]=useState(''),[input,setInput]=useState(''),[rows,setRows]=useState<Secret[]>([]),[selected,setSelected]=useState<Secret|null>(null),[name,setName]=useState(''),[environment,setEnvironment]=useState('local'),[kind,setKind]=useState('password'),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[truncated,setTruncated]=useState(false);
useEffect(()=>{const a=new AbortController();setRows([]);if(!tenant)return;setLoading(true);setError('');fetch('/api/mock-secrets?tenant='+encodeURIComponent(tenant),{signal:a.signal}).then(async r=>{if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(!Array.isArray(d.items))throw Error('INVALID_RESPONSE');setRows(d.items);setTruncated(d.truncated===true);}).catch(e=>{if(!a.signal.aborted)setError(String(e));}).finally(()=>{if(!a.signal.aborted)setLoading(false);});return()=>a.abort();},[tenant,revision]);
function reset(){setSelected(null);setName('');setEnvironment('local');setKind('password');setValue('');}
async function save(){if(busy)return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/mock-secrets'+(selected?'/'+selected.id:''),{method:selected?'PUT':'POST',headers:{'Content-Type':'application/json','X-Console-Action':'mock-secrets',...(selected?{'If-Match':'"'+selected.revision+'"'}:{})},body:JSON.stringify({tenant,environment,name,kind,value})});const d=await r.json();if(!r.ok)throw Error('HTTP '+r.status+' · '+d.error);reset();setNotice('Guardado en MockSecrets. Solo se devuelve la referencia.');setRevision(v=>v+1);}catch(e){setError(String(e)+' · '+t('Actualiza y consulta la revisión antes de repetir.'));}finally{setValue('');setBusy(false);}}
return <section className="page catalog-page blackout-page"><div className="page-heading"><div><span className="eyebrow">Sistema · MOCK LOCAL</span><h1>Secrets</h1><p>{t('MockSecrets: bóveda local para valores de prueba. Sin conexión a un Secret Manager externo.')}</p></div><button disabled={!tenant||busy||loading} onClick={()=>setRevision(v=>v+1)}>{t('Actualizar tabla')}</button></div><p>{t('Los valores no se muestran ni se exportan. Esta bóveda de desarrollo no tiene autenticación multiusuario; usa únicamente secretos sintéticos.')}</p><div className="catalog-toolbar"><label>{t('Cliente')}<input value={input} disabled={busy} onChange={e=>setInput(e.target.value)}/></label><button disabled={busy} onClick={()=>{setTenant(input.trim());reset();setNotice('');}}>{t('Seleccionar tenant')}</button></div>{error&&<p role="alert" className="catalog-error">{error}</p>}{notice&&<p role="status">{t(notice)}</p>}{loading&&<p role="status">{t('Cargando…')}</p>}{truncated&&<p>{t('Listado limitado a 500 registros.')}</p>}
{tenant&&<><div className="catalog-table-wrap"><table><thead><tr>{['Nombre','Entorno','Tipo','Revisión','Referencia','Detalle'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.environment}</td><td>{s.kind}</td><td>{s.revision}</td><td>{s.id}</td><td><button disabled={busy} onClick={()=>{setSelected(s);setName(s.name);setEnvironment(s.environment);setKind(s.kind);setValue('');setNotice('');}}>{t('Reemplazar valor')}</button></td></tr>)}</tbody></table></div><article className="blackout-editor"><h2>{t(selected?'Reemplazar valor':'Nuevo secreto')}</h2><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}><div className="blackout-fields"><label>{t('Nombre')}<input required pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,99}" value={name} disabled={!!selected} onChange={e=>setName(e.target.value)}/></label><label>{t('Entorno')}<input required pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,99}" value={environment} disabled={!!selected} onChange={e=>setEnvironment(e.target.value)}/></label><label>{t('Tipo')}<select value={kind} disabled={!!selected} onChange={e=>setKind(e.target.value)}><option>password</option><option>token</option></select></label><label>{t('Valor de prueba')}<input type="password" required maxLength={4096} autoComplete="new-password" value={value} onChange={e=>setValue(e.target.value)}/></label></div><button type="submit">{t('Guardar')}</button><button type="button" onClick={reset}>{t('Nuevo secreto')}</button></fieldset></form></article></>}</section>;
}
