import {useEffect,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {getSnapshot,type Query,type Snapshot,type Row} from './dashboard-data';
import '../catalog/catalog.css';
import '../blackouts/blackouts.css';
const initial:Query={tenant:'',status:'',q:'',page:1,limit:25};
export function IntegrationPluginPage({domain}:{domain:'gnm'|'cacf'}){
 const {t,locale}=useI18n();const [draft,setDraft]=useState(initial),[query,setQuery]=useState(initial),[data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[selected,setSelected]=useState<Row|null>(null);const title=domain==='gnm'?'GNM · Notifications':'CACF · Automations';
 useEffect(()=>{const abort=new AbortController();let active=true;const timer=setTimeout(()=>abort.abort(),12000);setLoading(true);setError('');setData(null);setSelected(null);getSnapshot(domain,query,abort.signal).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(abort.signal.aborted?'La consulta superó el tiempo de espera. Intenta actualizar.':e instanceof Error?e.message:'No se pudo consultar el dashboard.');}).finally(()=>{clearTimeout(timer);if(active)setLoading(false);});return()=>{active=false;clearTimeout(timer);abort.abort();};},[domain,query,revision]);
 const date=(v:string|null)=>v?new Date(v).toLocaleString(locale):'—';
 return <section className="page catalog-page blackout-page"><div className="page-heading"><div><span className="eyebrow">{t('Plugins')} · {domain==='gnm'?'Notifications':'CACF'}</span><h1>{title}</h1><p>{t(domain==='gnm'?'Consulta de notificaciones GNM y sus confirmaciones.':'Consulta de automatizaciones CACF y sus resultados.')}</p></div><button disabled={loading} onClick={()=>setRevision(v=>v+1)}>{t('Actualizar tabla')}</button></div><p>{t('Fuente')}: {data?data.source==='postgresql'?'PostgreSQL':t('API interna'):t('Sin verificar')} · {t('Última actualización')}: {date(data?.lastUpdatedAt??null)}</p><p>{t(domain==='gnm'?'Estados conocidos por la plataforma; los registros no equivalen a notificaciones únicas del proveedor.':'COMPLETED indica que la ejecución terminó; consulta Resultado para conocer su desenlace.')}</p>
 <form className="catalog-toolbar" onSubmit={e=>{e.preventDefault();setQuery({...draft,page:1});}}><label>{t('Cliente')}<input value={draft.tenant} maxLength={128} placeholder="Tenant / customer code" onChange={e=>setDraft({...draft,tenant:e.target.value})}/></label><label>{t('Estado')}<input value={draft.status} maxLength={128} onChange={e=>setDraft({...draft,status:e.target.value})}/></label><label>{t('Buscar identificador')}<input value={draft.q} maxLength={128} placeholder={t('Evento o referencia')} onChange={e=>setDraft({...draft,q:e.target.value})}/></label><button type="submit" disabled={loading}>{t('Buscar')}</button><button type="button" disabled={loading} onClick={()=>{setDraft(initial);setQuery(initial);}}>{t('Todos')}</button></form>
 {error&&<div className="catalog-error" role="alert">{t(error)}<button onClick={()=>setRevision(v=>v+1)}>{t('Reintentar')}</button></div>}{loading&&<p role="status">{t('Cargando…')}</p>}{data&&<><div className="blackout-actions"><strong>{data.total} {t(domain==='gnm'?'Registros de notificaciones':'Ejecuciones')}</strong>{Object.entries(data.counts).map(([status,n])=><button key={status} aria-pressed={query.status===status} onClick={()=>{setDraft({...draft,status});setQuery({...query,status,page:1});}}>{status} · {n}</button>)}</div><div className="catalog-table-wrap"><table><thead><tr>{['Evento / ID','Cliente','Estado','Referencia',...(domain==='cacf'?['Resultado']:[]),'Actualizado','Detalle'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><td>{r.eventId}<small>{r.id}</small></td><td>{r.tenant}{r.tenant==='DEMO-DASHBOARDS'&&<small>{t('Datos de demostración')}</small>}</td><td>{r.status}</td><td>{r.reference??'—'}</td>{domain==='cacf'&&<td>{r.outcome??t('Pendiente')}</td>}<td>{date(r.updatedAt)}</td><td><button aria-label={`${t('Ver detalle')} ${r.id}`} onClick={()=>setSelected(r)}>{t('Ver detalle')}</button></td></tr>)}</tbody></table>{!data.rows.length&&<p>{t('Sin registros')}</p>}</div><div className="blackout-actions"><button disabled={query.page===1||loading} onClick={()=>setQuery({...query,page:query.page-1})}>{t('Anterior')}</button><span>{t('Página')} {query.page}</span><button disabled={query.page*query.limit>=data.total||loading} onClick={()=>setQuery({...query,page:query.page+1})}>{t('Siguiente')}</button></div></>}
 {selected&&<article className="blackout-editor"><h2>{t('Detalle')} · {title}</h2><p>{t('Solo consulta')}</p><dl>{Object.entries(selected).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value??'—')}</dd></div>)}</dl><button onClick={()=>setSelected(null)}>{t('Cerrar')}</button></article>}</section>;
}
