#!/usr/bin/env bash
set -uo pipefail
ROOT=/opt/event-management-platform;TARGET="$ROOT/services/event-management-console";OVERLAY="$ROOT/infrastructure/docker-compose.event-management-console.yml";CONSOLE=event-management-console;CORE=event-integration-worker;LAB=event-itsm-ticketing-dashboard;TS="$(date -u +%Y%m%dT%H%M%SZ)";DIR="$ROOT/evidences/sn-ui-03/03.8-sre-safety/$TS";REPORT="$DIR/SN-UI-03.8-sre-safety-certification.txt";F=0;P=0
mkdir -p "$DIR";exec > >(tee -a "$REPORT") 2>&1;pass(){ echo "ASSERTION=PASS | $*";P=$((P+1));};fail(){ echo "ASSERTION=FAIL | $*";F=$((F+1));};inspect(){ docker inspect -f "$2" "$1" 2>/dev/null||true;}
echo "===== SN-UI-03.8 SRE AND OPERATIONAL SAFETY CERTIFICATION =====";echo "UTC=$TS";echo "MODE=READ_ONLY";echo "REPORT=$REPORT";cd "$ROOT"||exit 1
echo;echo "===== 01. GIT AND SCOPE GUARDS =====";[[ "$(git branch --show-current)" == feature/os-01-02-servicenow-core-foundation ]]&&pass "Correct branch"||fail "Unexpected branch";[[ "$(git rev-parse HEAD)" == b2475908289a427c6c1c9d728ee93d1d4ffa1c0c ]]&&pass "Certified baseline preserved"||fail "Unexpected HEAD";[[ "$(git diff --cached --name-only|sed '/^$/d'|wc -l|tr -d ' ')" == 0 ]]&&pass "Staging empty"||fail "Staging not empty";[[ -z "$(git status --porcelain -- services/integration-worker infrastructure/postgres)" ]]&&pass "Protected source unchanged"||fail "Protected source changed"
echo;echo "===== 02. CONSOLE RUNTIME =====";STATUS="$(inspect "$CONSOLE" '{{.State.Status}}')";HEALTH="$(inspect "$CONSOLE" '{{.State.Health.Status}}')";RESTARTS="$(inspect "$CONSOLE" '{{.RestartCount}}')";POLICY="$(inspect "$CONSOLE" '{{.HostConfig.RestartPolicy.Name}}')";IMAGE="$(inspect "$CONSOLE" '{{.Config.Image}}')";IMAGE_ID="$(inspect "$CONSOLE" '{{.Image}}')";OOM="$(inspect "$CONSOLE" '{{.State.OOMKilled}}')";echo "STATUS=$STATUS";echo "HEALTH=$HEALTH";echo "RESTARTS=$RESTARTS";echo "RESTART_POLICY=$POLICY";echo "IMAGE=$IMAGE";echo "IMAGE_ID=$IMAGE_ID";echo "OOM_KILLED=$OOM";[[ "$STATUS/$HEALTH/$RESTARTS" == running/healthy/0 ]]&&pass "Console healthy without restarts"||fail "Console runtime unstable";[[ "$POLICY" == unless-stopped ]]&&pass "Restart policy correct"||fail "Restart policy incorrect";[[ "$IMAGE" == event-management/event-management-console:1.0.0 ]]&&pass "Versioned image selected"||fail "Unexpected image";[[ "$OOM" == false ]]&&pass "No OOM termination"||fail "OOM termination detected"
echo;echo "===== 03. NETWORK AND PROCESS BOUNDARY =====";PORTS="$(inspect "$CONSOLE" '{{json .NetworkSettings.Ports}}')";NETWORKS="$(inspect "$CONSOLE" '{{range $k,$v := .NetworkSettings.Networks}}{{$k}} {{end}}')";MOUNTS="$(inspect "$CONSOLE" '{{len .Mounts}}')";ENV_COUNT="$(inspect "$CONSOLE" '{{len .Config.Env}}')";NO_NEW="$(inspect "$CONSOLE" '{{json .HostConfig.SecurityOpt}}')";echo "PORTS=$PORTS";echo "NETWORKS=$NETWORKS";echo "MOUNT_COUNT=$MOUNTS";echo "ENV_ENTRY_COUNT=$ENV_COUNT";echo "SECURITY_OPTIONS=$NO_NEW";echo "$PORTS"|grep -Fq '8090'&&pass "Only expected host publication captured"||fail "Port 8090 publication missing";echo "$NETWORKS"|grep -Fq event-management-net&&pass "Expected network attached"||fail "Expected network missing";[[ "$MOUNTS" == 0 ]]&&pass "Console has no host or persistent mounts"||fail "Unexpected mounts found";echo "$NO_NEW"|grep -Fq no-new-privileges&&pass "No-new-privileges enabled"||fail "No-new-privileges missing";[[ -z "$(grep -E '^[[:space:]]+depends_on:' "$OVERLAY" 2>/dev/null)" ]]&&pass "No runtime dependency declared"||fail "Unexpected depends_on declared"
echo;echo "===== 04. HTTP CONTRACT =====";curl -sS -D "$DIR/headers.txt" -o "$DIR/health.json" --max-time 5 http://localhost:8090/health||true;grep -Eq '^HTTP/[^ ]+ 200' "$DIR/headers.txt"&&pass "Health HTTP 200"||fail "Health HTTP response invalid";grep -Fiq 'X-Content-Type-Options: nosniff' "$DIR/headers.txt"&&pass "nosniff header present"||fail "nosniff header missing";grep -Fiq 'X-Frame-Options: SAMEORIGIN' "$DIR/headers.txt"&&pass "Frame policy header present"||fail "Frame policy header missing";grep -Fq '"status":"UP"' "$DIR/health.json"&&pass "Health payload UP"||fail "Health payload invalid"
echo;echo "===== 05. IMAGE AND STATIC CONTENT HYGIENE =====";IMAGE_SIZE="$(docker image inspect -f '{{.Size}}' "$IMAGE" 2>/dev/null||true)";echo "IMAGE_SIZE_BYTES=${IMAGE_SIZE:-UNKNOWN}";[[ "${IMAGE_SIZE:-0}" -gt 0 ]]&&pass "Image size captured"||fail "Image metadata unavailable";SECRET_MATCHES="$(grep -RInE '(password|secret|api[_-]?key|token)[[:space:]]*[:=][[:space:]]*[A-Za-z0-9+/]{12,}' "$TARGET/src" "$TARGET/nginx.conf" 2>/dev/null||true)";if [[ -z "$SECRET_MATCHES" ]];then pass "No credential-like assignments found in frontend source";else echo "$SECRET_MATCHES";fail "Potential credential material found";fi;docker logs --since 10m "$CONSOLE" >"$DIR/console.log" 2>&1||true;ERROR_COUNT="$(grep -Eic 'emerg|alert|crit|segfault|fatal' "$DIR/console.log"||true)";echo "CRITICAL_LOG_COUNT=$ERROR_COUNT";[[ "$ERROR_COUNT" == 0 ]]&&pass "No critical runtime log entries"||fail "Critical runtime logs detected";docker stats --no-stream --format 'NAME={{.Name}} CPU={{.CPUPerc}} MEM={{.MemUsage}} NET={{.NetIO}} PIDS={{.PIDs}}' "$CONSOLE"|tee "$DIR/container-stats.txt"||true
echo;echo "===== 06. PARALLEL PLATFORM SAFETY =====";LAB_HTTP="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 5 http://localhost:8088/itsm/tickets/ 2>/dev/null||true)";[[ "$(inspect "$LAB" '{{.State.Status}}')/$LAB_HTTP" == running/200 ]]&&pass "SN-UI-01 available"||fail "SN-UI-01 unavailable";CORE_STATE="$(inspect "$CORE" '{{.State.Status}}/{{.State.Health.Status}}/{{.RestartCount}}')";echo "CORE_STATE=$CORE_STATE";[[ "$CORE_STATE" == running/healthy/0 ]]&&pass "ServiceNow Core healthy and unrestarted"||fail "ServiceNow Core state unexpected"
echo;echo "===== FINAL RESULT =====";echo "READ_ONLY_CERTIFICATION=TRUE";echo "KAFKA_COMMANDS_PUBLISHED=FALSE";echo "KAFKA_OFFSET_MUTATION_ATTEMPTED=FALSE";echo "POSTGRESQL_QUERIES_EXECUTED=FALSE";echo "PASS_COUNT=$P";echo "FAILURE_COUNT=$F";echo "REPORT=$REPORT";if((F==0));then echo "SN_UI_03_8_SRE_SAFETY_CERTIFICATION=PASS";echo "NEXT_CHECKPOINT=SN-UI-03.9";exit 0;fi;echo "SN_UI_03_8_SRE_SAFETY_CERTIFICATION=FAIL";exit 1
