import {useI18n} from '../../shared/i18n/I18nProvider';
import {fields,operators,leaf,defaultValue,type Condition} from './policy.model';
export function ConditionEditor({value,onChange,path='1'}:{value:Condition;onChange:(value:Condition)=>void;path?:string}){
 const {t}=useI18n();const kind='all'in value?'all':'any'in value?'any':'not'in value?'not':'leaf';const children='all'in value?value.all:'any'in value?value.any:null;
 return <fieldset className="policy-condition"><legend>{t('Condición')} {path}</legend><label>{t('Estructura')}<select aria-label={`${t('Estructura')} ${path}`} value={kind} onChange={e=>onChange(e.target.value==='leaf'?leaf():e.target.value==='not'?{not:value}:e.target.value==='all'?{all:[value]}:{any:[value]})}><option value="leaf">{t('Predicado')}</option><option>all</option><option>any</option><option>not</option></select></label>
 {children?<>{children.map((c,i)=><div key={i}><ConditionEditor path={path+'.'+(i+1)} value={c} onChange={next=>onChange(kind==='all'?{all:children.map((x,n)=>i===n?next:x)}:{any:children.map((x,n)=>i===n?next:x)})}/><button disabled={children.length===1} onClick={()=>onChange(kind==='all'?{all:children.filter((_,n)=>i!==n)}:{any:children.filter((_,n)=>i!==n)})}>{t('Quitar condición')} {path}.{i+1}</button></div>)}<button onClick={()=>onChange(kind==='all'?{all:[...children,leaf()]}:{any:[...children,leaf()]})}>{t('Agregar condición')}</button></>:'not'in value?<ConditionEditor value={value.not} path={path+'.not'} onChange={not=>onChange({not})}/>:'field'in value?<div className="blackout-fields"><label>{t('Campo')}<select aria-label={`${t('Campo')} ${path}`} value={value.field} onChange={e=>onChange({field:e.target.value,operator:'EQ',value:defaultValue(e.target.value)})}>{Object.entries(fields).map(([f,type])=><option key={f} value={f}>{f} · {type}</option>)}</select></label><label>{t('Operador')}<select aria-label={`${t('Operador')} ${path}`} value={value.operator} onChange={e=>onChange({field:value.field,operator:e.target.value,...(['EXISTS','NOT_EXISTS'].includes(e.target.value)?{}:{value:['IN','NOT_IN'].includes(e.target.value)?[defaultValue(value.field)]:e.target.value==='BETWEEN'?[defaultValue(value.field),defaultValue(value.field)]:defaultValue(value.field)})})}>{operators(value.field).map(o=><option key={o}>{o}</option>)}</select></label>
 {!['EXISTS','NOT_EXISTS'].includes(value.operator)&&<div>{Array.isArray(value.value)?<>{value.value.map((v,i)=><div key={i}><Scalar field={value.field} value={v} label={`${t('Valor')} ${path}.${i+1}`} onChange={next=>onChange({...value,value:(value.value as unknown[]).map((x,n)=>i===n?next:x)})}/>{value.operator!=='BETWEEN'&&<button disabled={(value.value as unknown[]).length===1} onClick={()=>onChange({...value,value:(value.value as unknown[]).filter((_,n)=>n!==i)})}>{t('Quitar valor')} {i+1}</button>}</div>)}{value.operator!=='BETWEEN'&&<button disabled={(value.value as unknown[]).length>=128} onClick={()=>onChange({...value,value:[...value.value as unknown[],defaultValue(value.field)]})}>{t('Agregar valor')}</button>}</>:<Scalar field={value.field} value={value.value} label={`${t('Valor')} ${path}`} onChange={next=>onChange({...value,value:next})}/>}</div>}
 {value.operator==='REGEX'&&<p>{t('Regex de cadena completa: máximo 128 caracteres, sin grupos, alternancia ni escapes; un cuantificador simple como máximo. El backend valida la gramática.')}</p>}</div>:null}
 </fieldset>;
}
function Scalar({field,value,onChange,label}:{field:string;value:unknown;onChange:(value:unknown)=>void;label:string}){const type=fields[field];return <label>{label}{type==='boolean'?<select aria-label={label} value={String(value)} onChange={e=>onChange(e.target.value==='true')}><option>true</option><option>false</option></select>:<input aria-label={label} type={type==='number'?'number':'text'} step="any" value={value===undefined?'':String(value)} onChange={e=>onChange(type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/>}</label>;}
