import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {api,ApiError,type Operation} from '../blackouts/blackouts.api';
import {InventoryError} from '../inventory/InventoryPage';
import {PolicyEditor} from './PolicyEditor';
import {PolicySimulation} from './PolicySimulation';
import type {Policy,Row} from './policy.model';
import '../catalog/catalog.css';import '../blackouts/blackouts.css';import '../inventory/inventory.css';
const storage='console.policy.pending';
function stored():Operation|null{try{return JSON.parse(sessionStorage.getItem(storage)||'null');}catch{return null;}}
export function PolicyPage(){
 const {t}=useI18n();const [pending,setPending]=useState(stored),[tenant,setTenant]=useState(()=>stored()?.tenant??''),[input,setInput]=useState(()=>stored()?.tenant??''),[rows,setRows]=useState<Row[]>([]),[truncated,setTruncated]=useState(false),[loading,setLoading]=useState(false),[catalogError,setCatalogError]=useState<unknown>(),[error,setError]=useState<unknown>(),[query,setQuery]=useState(''),[legacy,setLegacy]=useState(false),[detail,setDetail]=useState<Row|null>(null),[selected,setSelected]=useState<string|null>(()=>stored()?.ruleId??null),[draft,setDraft]=useState<Policy|null>(null),[revision,setRevision]=useState(0),[editorKey,setEditorKey]=useState(0),[notice,setNotice]=useState(''),[conflict,setConflict]=useState(false),[busy,setBusy]=useState(false);const lock=useRef(false);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setCatalogError(undefined);fetch('/api/catalog/views/policies',{signal:abort.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new ApiError(r.status,'CATALOG_UNAVAILABLE');const data=await r.json();if(!Array.isArray(data.items))throw new ApiError(503,'INVALID_RESPONSE');if(!abort.signal.aborted){setRows(data.items);setTruncated(data.truncated===true);}}).catch(e=>{if(!abort.signal.aborted){setCatalogError(e);setRows([]);}}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[revision]);
 async function execute(op:Operation){if(lock.current)return;lock.current=true;setBusy(true);setError(undefined);setNotice('');try{sessionStorage.setItem(storage,JSON.stringify(op));setPending(op);await api(op.tenant,op.path,JSON.parse(op.body),op);sessionStorage.removeItem(storage);setPending(null);setSelected(op.ruleId);setConflict(false);setEditorKey(x=>x+1);setRevision(x=>x+1);setNotice(op.path==='/rules'?'Guardado, pendiente de activación. La versión activa anterior se conserva.':'Cambio confirmado por el servidor.');}catch(e){setError(e);if(op.path.endsWith('/enable'))setNotice('Versión guardada; activación pendiente de confirmar.');if(e instanceof ApiError&&[400,404,409,413,422,428].includes(e.status)){sessionStorage.removeItem(storage);setPending(null);if(e.status===409)setConflict(true);}}finally{lock.current=false;setBusy(false);}}
 const locked=busy||!!pending;const filtered=rows.filter(r=>(legacy?r.source!=='Event Processor':r.source==='Event Processor'&&r.configuration?.type==='POLICY')&&(!tenant||r.tenant===tenant)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
 return <section className="page catalog-page blackout-page"><div className="page-heading"><div><span className="eyebrow">Event Processor</span><h1>Policies</h1><p>{t('Políticas tipadas, propuestas y precedencia de directivas.')}</p></div><button disabled={loading||locked} onClick={()=>setRevision(x=>x+1)}>{t('Actualizar tabla')}</button></div><nav className="inventory-tabs" aria-label={t('Fuentes de políticas')}>{[[false,'Políticas del Processor'],[true,'Catálogo anterior · Solo consulta']].map(([value,label])=><button key={String(value)} disabled={locked} aria-pressed={legacy===value} onClick={()=>{setLegacy(Boolean(value));setSelected(null);setDraft(null);setDetail(null);setConflict(false);setNotice('');}}>{t(String(label))}</button>)}</nav>
 <div className="catalog-toolbar"><label>Tenant<input aria-label="Tenant" list="policy-tenants" value={input} disabled={locked} onChange={e=>setInput(e.target.value)}/></label><datalist id="policy-tenants">{[...new Set(rows.map(r=>r.tenant))].map(v=><option key={v}>{v}</option>)}</datalist><button disabled={locked} onClick={()=>{setTenant(input.trim());setSelected(null);setDraft(null);setDetail(null);setError(undefined);setConflict(false);setNotice('');}}>{t('Seleccionar tenant')}</button><input aria-label={t('Buscar en la tabla')} placeholder={t('Buscar en la tabla')} value={query} onChange={e=>setQuery(e.target.value)}/>{!legacy&&<button disabled={!tenant||locked} onClick={()=>{setSelected('');setEditorKey(x=>x+1);setConflict(false);setNotice('');}}>{t('Nueva política')}</button>}</div>
 <p>{tenant?`${t('Tenant seleccionado')}: ${tenant}`:t('Todos los tenants: selecciona uno para escribir o simular.')}</p><p>{t(legacy?'Catálogo PostgreSQL anterior: sus IDs no se envían al CRUD del Processor. No equivale a configuración ejecutable.':'Guardar no activa. Última versión y versión activa son independientes. Máximo 256 políticas activas por tenant.')}</p><InventoryError error={error}/><InventoryError error={catalogError}/>{notice&&<p className="blackout-notice" role="status">{t(notice)}</p>}{pending&&<div role="status"><p>{t('Operación pendiente de confirmar. Reintenta exactamente la misma solicitud antes de realizar otro cambio.')}</p><code>{pending.key}</code><button disabled={busy} onClick={()=>execute(pending)}>{t('Reintentar misma operación')}</button></div>}{truncated&&<p role="status">{t('Se muestran los primeros 2000 registros. El catálogo está incompleto.')}</p>}
 <div className="catalog-table-wrap" aria-busy={loading}><table><thead><tr>{['ID','Tenant','Fuente','Estado','Versión activa','Última guardada','Detalle'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.tenant+':'+r.id+':'+r.source}><td>{r.name??r.id}<small>{r.id}</small></td><td>{r.tenant}</td><td>{r.source}</td><td>{legacy?t('Solo consulta'):r.status}</td><td>{legacy?'—':r.active_version??'—'}</td><td>{legacy?'—':r.latest_version}</td><td><button disabled={!legacy&&(!tenant||locked)} aria-label={`${t(legacy?'Ver detalle':'Abrir política')} ${r.id}`} onClick={()=>{if(legacy)setDetail(r);else{setSelected(r.id);setEditorKey(x=>x+1);setConflict(false);setNotice('');}}}>{t(legacy?'Ver detalle':'Abrir')}</button></td></tr>)}</tbody></table>{loading?<p role="status">{t('Cargando…')}</p>:!filtered.length&&<p>{t('Sin registros')}</p>}</div>
 {legacy&&detail&&<article className="blackout-editor"><h2>{t('Detalle')} · {detail.id}</h2><p>{t('Solo consulta')}</p><pre>{JSON.stringify(detail,null,2)}</pre><button onClick={()=>setDetail(null)}>{t('Cerrar')}</button></article>}
 {!legacy&&tenant&&<>{selected!==null&&<PolicyEditor key={tenant+':'+selected+':'+editorKey} tenant={tenant} id={selected} locked={locked} conflict={conflict} onDraft={setDraft} execute={execute} reconcile={()=>{setConflict(false);setError(undefined);setEditorKey(x=>x+1);setRevision(x=>x+1);}}/>}<details><summary>{t('Cómo se resuelven las propuestas')}</summary><p>{t('Todas las coincidencias aportan propuestas. Prioridad descendente, ID y versión ordenan la evaluación; la directiva más restrictiva prevalece.')}</p><p>DEAD_LETTER &gt; STATE_ONLY &gt; SUPPRESS_INTEGRATIONS &gt; CORRELATE_ONLY &gt; GENERATE_COMMANDS &gt; CONTINUE</p><p>{t('POLICY solo propone CONTINUE, STATE_ONLY, SUPPRESS_INTEGRATIONS y CORRELATE_ONLY. No crea tickets ni comandos.')}</p><p>{t('STATE_ONLY bloquea Routing; no revierte Correlación ni elimina auditoría. Los campos ausentes no coinciden con predicados ordinarios; not niega su hijo.')}</p></details><PolicySimulation key={tenant} tenant={tenant} draft={draft} revision={revision}/></>}
 </section>;
}
