import {createUuid} from '../../shared/utils/uuid';
import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {api,ApiError,instant} from '../blackouts/blackouts.api';
import {InventoryError} from '../inventory/InventoryPage';
import {validatePolicy,type Policy} from './policy.model';
type AnyRule={id:string;version:number;type?:string;strategy?:string;[key:string]:unknown};
type Stage={stage:string;status:string;match:string;directive:string;reason:string;evidence:Record<string,unknown>};
type Result={directive:string;configurationSource:string;snapshotChecksum:string;stages:Stage[];[key:string]:unknown};
export function PolicySimulation({tenant,draft,revision}:{tenant:string;draft:Policy|null;revision:number}){
 const {t}=useI18n();const [mode,setMode]=useState('ACTIVE'),[rules,setRules]=useState<AnyRule[]>([]),[selected,setSelected]=useState<string[]>([]),[includeDraft,setIncludeDraft]=useState(false),[reading,setReading]=useState(false),[readCount,setReadCount]=useState(0),[readError,setReadError]=useState<unknown>(),[complete,setComplete]=useState(false),[node,setNode]=useState('router-1'),[component,setComponent]=useState(''),[severity,setSeverity]=useState(1),[action,setAction]=useState('OPEN'),[at,setAt]=useState(()=>new Date().toISOString()),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[result,setResult]=useState<{data:Result;revision:number;mode:string}>(),[processingId,setProcessingId]=useState(''),[explain,setExplain]=useState<unknown>(),[explainError,setExplainError]=useState<unknown>(),[explaining,setExplaining]=useState(false);
 const request=useRef<AbortController>(),listing=useRef<AbortController>();useEffect(()=>()=>{request.current?.abort();listing.current?.abort();},[]);
 async function read(){if(listing.current)return;const abort=new AbortController();listing.current=abort;setReading(true);setReadError(undefined);setComplete(false);setRules([]);setSelected([]);setReadCount(0);try{let cursor:string|number|undefined;const seen=new Set<string>(),found:AnyRule[]=[];do{const {data}=await api<{items:{id:string}[];next:string|number|null}>(tenant,'/rules?limit=50'+(cursor===undefined?'':'&after='+encodeURIComponent(cursor)),undefined,undefined,abort.signal);if(!Array.isArray(data.items))throw new ApiError(503,'INVALID_RESPONSE');for(let i=0;i<data.items.length;i+=4){const batch=await Promise.all(data.items.slice(i,i+4).map(async r=>(await api<{rule:AnyRule}>(tenant,'/rules/'+encodeURIComponent(r.id),undefined,undefined,abort.signal)).data.rule));found.push(...batch);if(abort.signal.aborted)return;setRules([...found]);setReadCount(found.length);}cursor=data.next??undefined;if(cursor!==undefined){if(seen.has(String(cursor)))throw new ApiError(503,'REPEATED_CURSOR');seen.add(String(cursor));}}while(cursor!==undefined&&!abort.signal.aborted);if(!abort.signal.aborted)setComplete(true);}catch(e){if(!abort.signal.aborted)setReadError(e);}finally{if(!abort.signal.aborted)setReading(false);listing.current=undefined;}}
 async function run(){if(request.current)return;const abort=new AbortController();request.current=abort;setBusy(true);setError(undefined);try{if(!node.trim()||!Number.isInteger(severity)||severity<0||severity>5)throw new Error('Recurso obligatorio y severidad entera de 0 a 5.');const event={schemaVersion:'1.1',eventId:createUuid(),eventKey:node,tenant:{code:tenant},resource:{name:node,...(component?{component}:{})},summary:'Policy frontend simulation',lifecycleAction:action,effectiveSeverity:severity,timestamps:{receivedAt:instant(at)}};const candidates=new Map<string,unknown>(rules.filter(r=>selected.includes(r.id)).map(r=>[r.id,r]));if(mode==='CANDIDATE' && includeDraft){if(!draft)throw new Error('No hay un borrador disponible para esta simulación.');candidates.set(draft.id,validatePolicy(draft));}if(mode==='CANDIDATE'&&(!candidates.size||candidates.size>256))throw new Error('Selecciona de 1 a 256 definiciones candidatas.');const {data}=await api<Result>(tenant,'/simulations',{event,...(mode==='CANDIDATE'?{candidateRules:[...candidates.values()]}:{})},undefined,abort.signal);if(!abort.signal.aborted)setResult({data,revision,mode});}catch(e){if(!abort.signal.aborted){setError(e);setResult(undefined);}}finally{if(!abort.signal.aborted)setBusy(false);request.current=undefined;}}
 const stage=result?.data.stages.find(s=>s.stage==='PolicyEvaluation');const evidence=stage?.evidence??{};const indexes=[...new Set(Object.keys(evidence).map(k=>/^rule\.(\d+)\./.exec(k)?.[1]).filter((x):x is string=>!!x))].sort((a,b)=>Number(a)-Number(b));
 return <><article className="blackout-editor"><h2>{t('Simulación de políticas')}</h2><p>{t('La candidata reemplaza todo el snapshot. Incluye otras capacidades necesarias. La simulación no envía comandos ni escribe grupos.')}</p><fieldset disabled={busy}><label>{t('Modo de simulación')}<select value={mode} onChange={e=>setMode(e.target.value)}><option value="ACTIVE">{t('Reglas activas')}</option><option value="CANDIDATE">{t('Conjunto candidato')}</option></select></label>{mode==='CANDIDATE'&&<><button disabled={reading} onClick={read}>{t('Consultar definiciones candidatas')}</button><p role="status">{t('Definiciones')}: {readCount} · {t(reading?'Leyendo definiciones…':complete?'Lectura finalizada':'Lectura pendiente')}</p><InventoryError error={readError}/>{readError&&<p>{t('Listado incompleto: corrige los errores y actualiza.')}</p>}{rules.map(r=><label className="inventory-check" key={r.id}><input type="checkbox" disabled={!complete} aria-label={`${t('Candidato')} ${r.id}`} checked={selected.includes(r.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/>{r.id} · {r.type??r.strategy} · {t('Última guardada')} v{r.version}</label>)}<label className="inventory-check"><input type="checkbox" disabled={!draft} checked={includeDraft} onChange={e=>setIncludeDraft(e.target.checked)}/>{t('Incluir borrador abierto')}</label><p>{t('El borrador reemplaza la versión seleccionada del mismo ID. Cada escritura se confirma por separado.')}</p></>}
 <div className="blackout-fields"><label>{t('Recurso de prueba')}<input value={node} onChange={e=>setNode(e.target.value)}/></label><label>component<input value={component} onChange={e=>setComponent(e.target.value)}/></label><label>{t('Severidad')}<input type="number" min={0} max={5} value={severity} onChange={e=>setSeverity(e.target.value===''?NaN:Number(e.target.value))}/></label><label>lifecycleAction<select value={action} onChange={e=>setAction(e.target.value)}><option>OPEN</option><option>CLOSE</option></select></label><label>{t('Instante de evaluación ISO')}<input value={at} onChange={e=>setAt(e.target.value)}/></label></div><button onClick={run}>{t('Simular políticas')}</button></fieldset><InventoryError error={error}/>
 {result&&<section role="status"><p>{result.mode} · Tenant: {tenant} · directive: <strong>{result.data.directive}</strong></p>{result.revision!==revision&&<p>{t('La configuración cambió desde esta consulta. Vuelve a simular para ver el estado actual.')}</p>}<p>PolicyEvaluation: {stage?.status} · {stage?.match} · {stage?.reason}</p><p>snapshotChecksum: {String(evidence.snapshotChecksum??result.data.snapshotChecksum)} · fieldContractVersion: {String(evidence.fieldContractVersion??'—')} · ruleCount: {String(evidence.ruleCount??'—')} · resolvedDirective: {String(evidence.resolvedDirective??'—')}</p>{stage?.status==='FAILED'&&<div role="alert"><pre>{JSON.stringify({failedRuleId:evidence.failedRuleId,failedRuleVersion:evidence.failedRuleVersion,errorCode:evidence.errorCode},null,2)}</pre></div>}<div className="catalog-table-wrap"><table aria-label={t('Resultados de políticas')}><thead><tr>{['id','version','checksum','match','conditions','proposals'].map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{indexes.map(i=><tr key={i}>{['id','version','checksum','match','conditions','proposals'].map(k=><td key={k}>{String(evidence[`rule.${i}.${k}`]??'—')}</td>)}</tr>)}</tbody></table></div><details><summary>{t('Etapas y evidencia')}</summary><pre>{JSON.stringify(result.data,null,2)}</pre></details></section>}
 </article><article className="blackout-editor"><h2>{t('Evidencia de evento real')}</h2><label>processingId<input value={processingId} onChange={e=>setProcessingId(e.target.value)}/></label><button disabled={explaining||!processingId.trim()} onClick={async()=>{setExplaining(true);setExplainError(undefined);setExplain(undefined);try{setExplain((await api(tenant,'/explain/'+encodeURIComponent(processingId.trim()))).data);}catch(e){setExplainError(e);}finally{setExplaining(false);}}}>{t('Consultar evidencia')}</button><InventoryError error={explainError}/>{explain!==undefined&&<pre>{JSON.stringify(explain,null,2)}</pre>}</article></>;
}
