import {useEffect,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {api,ApiError,operation,type Operation} from '../blackouts/blackouts.api';
import {History} from '../blackouts/BlackoutsPage';
import {InventoryError} from '../inventory/InventoryPage';
import {ConditionEditor} from './ConditionEditor';
import {actions,newPolicy,validatePolicy,type Policy,type Registry} from './policy.model';
export function PolicyEditor({tenant,id,locked,conflict,onDraft,execute,reconcile}:{tenant:string;id:string;locked:boolean;conflict:boolean;onDraft:(r:Policy|null)=>void;execute:(o:Operation)=>Promise<void>;reconcile:()=>void}){
 const {t}=useI18n();const [rule,setPolicy]=useState<Policy>(newPolicy),[record,setRecord]=useState<Registry>(),[etag,setEtag]=useState('"0"'),[loading,setLoading]=useState(!!id),[error,setError]=useState<unknown>(),[reason,setReason]=useState(''),[confirmation,setConfirmation]=useState<Operation|null>(null),[valid,setValid]=useState(false),[validating,setValidating]=useState(false),[active,setActive]=useState<Policy>(),[json,setJson]=useState('');
 useEffect(()=>{if(!id)return;const abort=new AbortController();api<Registry>(tenant,'/rules/'+encodeURIComponent(id),undefined,undefined,abort.signal).then(({data,etag})=>{if(abort.signal.aborted)return;if(data.rule.type!=='POLICY'||!etag)throw new ApiError(422,'WRONG_RULE_TYPE');setRecord(data);setEtag(etag);setPolicy({...data.rule,version:data.latestVersion+1});}).catch(e=>{if(!abort.signal.aborted)setError(e);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[tenant,id]);
 useEffect(()=>{onDraft(loading||id&&!record?null:rule);return()=>onDraft(null);},[rule,loading,id,record,onDraft]);
 const blocked=locked||loading||!!id&&!record||conflict||record?.status==='RETIRED'||!!confirmation||validating;
 function change(r:Policy){setPolicy(r);setValid(false);setError(undefined);}
 async function check(){setValidating(true);setError(undefined);try{await api(tenant,'/rules/validate',{rule:validatePolicy(rule)});setValid(true);}catch(e){setError(e);}finally{setValidating(false);}}
 function prepare(action:string){try{setError(undefined);if(!reason.trim()||reason.length>2048)throw new Error('Motivo de cambio obligatorio, máximo 2048 caracteres.');const path=action==='save'?'/rules':'/rules/'+encodeURIComponent(id)+'/'+action;setConfirmation(operation(tenant,path,action==='save'?{rule:validatePolicy(rule),reason}:{version:action==='enable'?record!.latestVersion:record!.activeVersion??record!.latestVersion,reason},etag,rule.id));}catch(e){setError(e);}}
 return <article className="blackout-editor"><h2>{t('Política')} · {id||t('Nuevo')}</h2><InventoryError error={error}/>{record&&<p>{t('Estado')}: {record.status} · {t('Versión activa')}: {record.activeVersion??'—'} · {t('Última guardada')}: {record.latestVersion} · ETag {etag}</p>}{id&&<button disabled={locked||!!confirmation} onClick={reconcile}>{t('Cargar revisión actual y descartar borrador')}</button>}{conflict&&<p role="alert">{t('Tu borrador se conserva. Carga la revisión actual antes de preparar otra operación.')}</p>}{record?.activeVersion&&<button onClick={async()=>{try{const {data}=await api<Registry>(tenant,'/rules/'+encodeURIComponent(id)+'?version='+record.activeVersion);setActive(data.rule);}catch(e){setError(e);}}}>{t('Consultar definición activa')}</button>}{active&&<details open><summary>{t('Definición activa')}</summary><pre>{JSON.stringify(active,null,2)}</pre></details>}
 <fieldset disabled={blocked}><legend>{t('Nueva versión de la definición')}</legend><div className="blackout-fields"><label>ID<input aria-label="Policy ID" disabled={!!id} value={rule.id} onChange={e=>change({...rule,id:e.target.value})}/></label><label>{t('Prioridad')}<input type="number" value={rule.priority} onChange={e=>change({...rule,priority:Number(e.target.value)})}/></label><label>{t('Responsable')}<input value={rule.metadata.owner} onChange={e=>change({...rule,metadata:{...rule.metadata,owner:e.target.value}})}/></label><label>{t('Descripción')}<textarea value={rule.metadata.description??''} onChange={e=>change({...rule,metadata:{...rule.metadata,description:e.target.value}})}/></label><label>{t('Etiquetas, una por línea')}<textarea value={rule.metadata.tags?.join('\n')??''} onChange={e=>change({...rule,metadata:{...rule.metadata,tags:e.target.value.split('\n').filter(Boolean)}})}/></label></div>
 <ConditionEditor value={rule.condition} onChange={condition=>change({...rule,condition})}/><h3>{t('Propuestas de directiva')}</h3>{rule.actions.map((action,i)=><div className="blackout-actions" key={i}><label>{t('Acción')} {i+1}<select aria-label={`${t('Acción')} ${i+1}`} value={action.type} onChange={e=>change({...rule,actions:rule.actions.map((a,n)=>i===n?{type:e.target.value}:a)})}>{actions.map(a=><option key={a}>{a}</option>)}</select></label><button disabled={rule.actions.length===1} onClick={()=>change({...rule,actions:rule.actions.filter((_,n)=>i!==n)})}>{t('Quitar acción')} {i+1}</button></div>)}<button disabled={rule.actions.length>=16} onClick={()=>change({...rule,actions:[...rule.actions,{type:'CONTINUE'}]})}>{t('Agregar acción')}</button>
 <label className="inventory-check"><input type="checkbox" checked={rule.enabled} onChange={e=>change({...rule,enabled:e.target.checked})}/>{t('Versión habilitable (no activa al guardar)')}</label><button onClick={check}>{t('Validar definición')}</button>
 <details><summary>{t('Validar definición JSON')}</summary><p>{t('El JSON debe pertenecer a esta política y versión. Se valida en el backend antes de incorporarlo al formulario.')}</p><button onClick={()=>setJson(JSON.stringify(rule,null,2))}>{t('Copiar borrador a JSON')}</button><label>{t('Definición JSON')}<textarea aria-label={t('Definición JSON')} rows={12} value={json} onChange={e=>setJson(e.target.value)}/></label><button onClick={async()=>{setError(undefined);setValidating(true);try{const parsed=JSON.parse(json);if(parsed.type!=='POLICY'||parsed.version!==rule.version||id&&parsed.id!==id)throw new Error('ID, tipo o versión no corresponde al borrador.');await api(tenant,'/rules/validate',{rule:parsed});change(validatePolicy(parsed));setValid(true);}catch(e){setError(e);}finally{setValidating(false);}}}>{t('Validar e incorporar JSON')}</button></details>
 </fieldset>

 {valid&&<p role="status">{t('Definición válida. Aún no está guardada.')}</p>}<fieldset disabled={blocked}><legend>{t('Operaciones de la configuración')}</legend><label>{t('Motivo del cambio')}<textarea value={reason} maxLength={2048} onChange={e=>setReason(e.target.value)}/></label><div className="blackout-actions"><button onClick={()=>prepare('save')}>{t('Guardar nueva versión')}</button>{record&&<><button disabled={!record.rule.enabled} onClick={()=>prepare('enable')}>{t('Activar última guardada')}</button><button onClick={()=>prepare('disable')}>{t('Desactivar')}</button><button onClick={()=>prepare('retire')}>{t('Retirar')}</button></>}</div></fieldset>{record?.status==='RETIRED'&&<p>{t('Retirado: estado terminal. El historial se conserva.')}</p>}
 {confirmation&&<section className="blackout-confirm" aria-label={t('Confirmar operación')}><h3>{t('Confirmar operación')}</h3><p>Tenant: {tenant} · ID: {rule.id} · If-Match: {etag}</p><p>{t(confirmation.path==='/rules'?'Guardar no activa. La versión activa anterior seguirá ejecutándose.':confirmation.path.endsWith('/retire')?'Retirar es terminal y bloquea la reactivación.':'Esta operación cambia el estado operativo de la regla guardada.')}</p>{confirmation.path.endsWith('/disable')&&<p>{t('Desactivar detiene la evaluación de esta política.')}</p>}<pre>{confirmation.body}</pre><button disabled={locked} onClick={()=>{const op=confirmation;setConfirmation(null);void execute(op);}}>{t('Confirmar envío')}</button><button disabled={locked} onClick={()=>setConfirmation(null)}>{t('Cancelar')}</button></section>}{record&&<History tenant={tenant} id={id}/>}</article>;
}
