export const fields:Record<string,'string'|'number'|'boolean'|'instant'>={'event.identifier':'string','event.key':'string','event.status':'string','event.severity':'number','event.receivedAt':'instant','tenant.customerCode':'string','resource.node':'string','resource.component':'string','enrichment.resource.ciId':'string','enrichment.service.name':'string','enrichment.assignment.group':'string','enrichment.location.site':'string','enrichment.resource.class':'string','enrichment.resource.managed':'boolean','enrichment.service.criticality':'number'};
export const actions=['CONTINUE','STATE_ONLY','SUPPRESS_INTEGRATIONS','CORRELATE_ONLY'];
export type Condition={field:string;operator:string;value?:unknown}|{all:Condition[]}|{any:Condition[]}|{not:Condition};
export type Policy={id:string;version:number;type:'POLICY';enabled:boolean;priority:number;condition:Condition;actions:{type:string}[];metadata:{owner:string;description?:string;tags?:string[]}};
export type Registry={id:string;latestVersion:number;activeVersion:number|null;status:string;revision:number;rule:Policy;checksum:string};
export type Row={id:string;name?:string;tenant:string;source:string;status?:string;active_version?:number|null;latest_version?:number;configuration?:Policy;[key:string]:unknown};
export const leaf=():Condition=>({field:'event.severity',operator:'LTE',value:1});
export const newPolicy=():Policy=>({id:'',version:1,type:'POLICY',enabled:true,priority:10,condition:leaf(),actions:[{type:'SUPPRESS_INTEGRATIONS'}],metadata:{owner:'operations'}});
export function operators(field:string){const type=fields[field];return ['EQ','NE','IN','NOT_IN','EXISTS','NOT_EXISTS',...(type==='number'||type==='instant'?['GT','GTE','LT','LTE','BETWEEN']:[]),...(type==='string'?['CONTAINS','STARTS_WITH','ENDS_WITH','REGEX']:[])];}
export function defaultValue(field:string){return fields[field]==='number'?0:fields[field]==='boolean'?false:fields[field]==='instant'?new Date().toISOString():'';}
export function validateCondition(c:Condition,depth=0):void{
 if(!c||typeof c!=='object'||depth>32)throw new Error('Condición inválida o demasiado profunda.');
 for(const group of ['all','any'] as const)if(group in c){const children=(c as {all?:Condition[];any?:Condition[]})[group];if(Object.keys(c).length!==1||!Array.isArray(children)||!children.length)throw new Error('El grupo requiere condiciones.');children.forEach(x=>validateCondition(x,depth+1));return;}
 if('not'in c){if(Object.keys(c).length!==1)throw new Error('Condición inválida o demasiado profunda.');validateCondition(c.not,depth+1);return;}
 if(!('field'in c)||!fields[c.field]||!operators(c.field).includes(c.operator)||Object.keys(c).some(k=>!['field','operator','value'].includes(k)))throw new Error('Campo u operador fuera del contrato.');
 if(['EXISTS','NOT_EXISTS'].includes(c.operator)){if('value'in c)throw new Error('EXISTS y NOT_EXISTS no admiten valor.');return;}
 const collection=['IN','NOT_IN','BETWEEN'].includes(c.operator),values=collection?c.value:[c.value];if(!Array.isArray(values)||!values.length||values.length>128)throw new Error('Se requiere una colección homogénea de 1 a 128 valores.');
 const type=fields[c.field];for(const value of values){if(type==='number'?typeof value!=='number'||!Number.isFinite(value):type==='boolean'?typeof value!=='boolean':typeof value!=='string'||value.length>4096)throw new Error('El valor debe respetar el tipo del campo, sin coerción.');if(type==='instant'&&(!/^\d{4}-\d\d-\d\dT.*(Z|[+-]\d\d:\d\d)$/.test(String(value))||!Number.isFinite(Date.parse(String(value)))))throw new Error('Usa fecha ISO 8601 con Z u offset explícito.');}
 if(c.operator==='BETWEEN'&&(values.length!==2||(type==='instant'?Date.parse(String(values[0]))>Date.parse(String(values[1])):Number(values[0])>Number(values[1]))))throw new Error('BETWEEN requiere dos límites ordenados.');
 if(c.operator==='REGEX'){const s=String(c.value);if(s.length>128||/[(){}|\\]/.test(s)||(s.match(/[*+?]/g)||[]).length>1)throw new Error('Regex no admitida: sin grupos, alternancia, escapes ni múltiples cuantificadores.');}
}
export function validatePolicy(p:Policy){if(p.type!=='POLICY'||!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(p.id))throw new Error('ID o tipo de política inválido.');if(!Number.isSafeInteger(p.priority)||!p.metadata.owner.trim())throw new Error('Completa responsable y prioridad entera.');validateCondition(p.condition);if(!p.actions.length||p.actions.length>16||p.actions.some(a=>!actions.includes(a.type)||Object.keys(a).some(k=>k!=='type')))throw new Error('Selecciona de 1 a 16 acciones permitidas.');return p;}
