import {useEffect,useState} from 'react';
import {useI18n} from './i18n';
type Api={id:string;service:string;consumers:string;endpoint:string;probeUrl:string;status:string;httpStatus:number|null;latencyMs:number;checkedAt:string;actions:string[]};
type Operation={id:string;service:string;action:string;status:string};
async function request(path:string,body?:unknown){const r=await fetch(path,{signal:AbortSignal.timeout(15000),...(body?{method:'POST',headers:{'Content-Type':'application/json','X-Console-Action':'1'},body:JSON.stringify(body)}:{})});if(!r.ok)throw new Error(r.status===409?'Hay una operación en curso.':'No se pudo consultar el dashboard.');return r.json();}
export function ApiManagementPage(){
 const {t,locale}=useI18n();const [rows,setRows]=useState<Api[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[operation,setOperation]=useState<Operation|null>(null),[revision,refresh]=useState(0);
 useEffect(()=>{let active=true;setBusy(true);request('/api/administration/apis').then(d=>{if(active){setRows(d.apis);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[revision]);
 useEffect(()=>{if(operation?.status!=='running')return;let active=true;const timer=setInterval(()=>{request('/api/administration/operations/'+operation.id).then(d=>{if(active){setOperation(d);if(d.status!=='running')refresh(v=>v+1);}}).catch(e=>{if(active)setError(e.message);});},2000);return()=>{active=false;clearInterval(timer);};},[operation?.id,operation?.status]);
 async function act(api:Api,action:string){setBusy(true);setError('');try{const result=await request('/api/administration/apis/actions',{id:crypto.randomUUID(),apiId:api.id,action});if(action==='testing')setRows(old=>old.map(r=>r.id===api.id?result:r));else setOperation(result);}catch(e){setError(e instanceof Error?e.message:'No se pudo consultar el dashboard.');}finally{setBusy(false);}}
 return <main id="content" aria-busy={busy}><div className="heading"><div><span className="eyebrow">07 / {t('Administración')}</span><h1>API Management</h1><p>{t('Disponibilidad HTTP y control de los servicios que alojan las APIs.')}</p></div><button disabled={busy} onClick={()=>refresh(v=>v+1)}>{t('↻ Actualizar')}</button></div><p>{t('Testing comprueba el endpoint de salud. Stop, start y reboot afectan al servicio completo y a todas sus APIs.')}</p><p>{t('Las APIs sin control local sólo permiten testing.')}</p>{error&&<div role="alert" className="error">{t(error)}</div>}{operation&&<div role="status" className="source-line">{operation.service} · {operation.action} · {t(operation.status)} · {operation.id}</div>}<div className="summary"><article className="total"><span>APIs</span><strong>{rows.length}</strong></article><article className="distribution"><h2>{t('Estado')}</h2>{['UP','DOWN','UNREACHABLE'].map(s=><div className="state-row" key={s}><span>{s}</span><strong>{rows.filter(r=>r.status===s).length}</strong></div>)}</article></div><section className="records"><div className="table-scroll"><table><thead><tr><th>API / {t('Servicio')}</th><th>{t('Consumidores')}</th><th>{t('Verificación')}</th><th>{t('Estado')}</th><th>{t('Acciones')}</th></tr></thead><tbody>{rows.map(api=><tr key={api.id}><td><strong>{api.id}</strong><small>{api.service}</small><small>{api.endpoint}</small></td><td>{api.consumers}</td><td><small>{api.probeUrl}</small><small>{new Date(api.checkedAt).toLocaleString(locale)}</small></td><td><span className="status">{api.status}</span><small>HTTP {api.httpStatus??'—'} · {api.latencyMs} ms</small></td><td><div className="api-actions">{api.actions.map(action=><button className="secondary" key={action} disabled={busy||operation?.status==='running'} onClick={()=>act(api,action)}>{action}</button>)}</div></td></tr>)}</tbody></table></div></section></main>;
}
