import {createContext, useContext, useEffect, useState, type ReactNode} from "react";

export type Language = "es" | "en";
export const english: Record<string,string> = {
  "Eventos con integración GLPI": "Events with GLPI integration",
  "Estado y referencias de tickets GLPI.": "GLPI ticket status and references.",
  "Revisar resultados pendientes y fallidos": "Review pending and failed results",
  "Verificar el ID nativo de GLPI": "Verify the native GLPI ID",
  "Revisar comandos pendientes de reconciliación": "Review commands awaiting reconciliation",

"Iniciar servicio":"Start service", "Detener servicio":"Stop service", "Reiniciar servicio":"Restart service", "Probar conexión":"Test connection", "Actualizar":"Refresh", "Buscar API":"Search APIs", "Nombre, servicio o ruta":"Name, service or route", "Comprobación del endpoint":"Endpoint check", "Salud del servicio":"Service health",

"Perfil": "Profile", "Cerrar perfil": "Close profile", "Operador local": "Local operator", "Idioma": "Language", "Preferencias guardadas en este navegador.": "Preferences saved in this browser.", "Console local": "Local console", "Abrir menú": "Open menu", "Cerrar menú": "Close menu", "Ajustar ancho del menú": "Resize navigation menu", "Arrastra para ajustar. Flechas para cambiar ancho; doble clic para restablecer.": "Drag to resize. Use arrow keys to adjust width; double-click to reset.",
"Tema":"Theme", "Actual":"Current",
"Administración":"Administration", "Operación y administración":"Operations and administration", "Disponibilidad HTTP y control de los servicios que alojan las APIs.":"HTTP availability and control of API hosting services.", "Testing comprueba el endpoint de salud. Stop, start y reboot afectan al servicio completo y a todas sus APIs.":"Testing checks the health endpoint. Stop, start and reboot affect the entire service and all its APIs.", "Las APIs sin control local sólo permiten testing.":"APIs without local control only support testing.", "Hay una operación en curso.":"An operation is in progress.", "Servicio":"Service", "Consumidores":"Consumers", "Verificación":"Verification", "Acciones":"Actions", "running":"Running", "succeeded":"Succeeded", "failed":"Failed", "interrupted":"Interrupted",
"Eventos originales recibidos, antes de normalizar o publicar en Kafka.":"Original events received, before normalization or publication to Kafka.", "Hoy e histórico usan la zona America/Mexico_City. La captura comienza con este despliegue.":"Today and history use America/Mexico_City time. Capture starts with this deployment.", "Periodo":"Period", "Hoy":"Today", "Histórico":"History", "Desde":"From", "Hasta":"Through", "Recepción":"Received", "Original":"Original", "Ver original":"View original", "Descargar original":"Download original",

  "Eventos":"Events", "Agregados de eventos":"Event aggregates", "Estado operativo y ciclo de vida de los eventos.":"Operational state and event lifecycle.",
  "Revisar eventos abiertos y severidad efectiva":"Review open events and effective severity", "Identificar repeticiones con el contador tally":"Identify repetitions using the tally counter", "Consultar cierres en el estado consolidado":"Check closures in consolidated state",
  "Eventos con integración ITSM":"Events with ITSM integration", "Seguimiento de solicitudes y resultados conocidos por la plataforma. No representa tickets únicos del proveedor.":"Requests and results known to the platform. These are not unique provider tickets.",
  "Revisar estados pendientes y fallidos":"Review pending and failed states", "Verificar referencias de ticket disponibles":"Check available ticket references", "Consultar reconciliaciones con el equipo de integración":"Review reconciliations with the integration team",
  "Eventos con integración GNM":"Events with GNM integration", "Notificaciones y confirmaciones conocidas por la plataforma. No representa incidentes únicos de Everbridge.":"Notifications and confirmations known to the platform. These are not unique Everbridge incidents.",
  "Revisar estados de apertura y confirmación":"Review opening and confirmation states", "Identificar notificaciones sin referencia":"Identify notifications without a reference", "Revisar fallos y cierres confirmados":"Review failures and confirmed closures",
  "Ejecuciones de automatización":"Automation executions", "Ejecuciones, callbacks y resultados de automatización. COMPLETED indica término; el resultado determina su éxito.":"Automation executions, callbacks and outcomes. COMPLETED means finished; the outcome determines success.",
  "Revisar ejecuciones en curso y callbacks pendientes":"Review running executions and pending callbacks", "Identificar vencimientos y fallos de envío":"Identify timeouts and submission failures", "Revisar el resultado de cada ejecución terminada":"Review the outcome of each finished execution",
  "Sin registros":"No records", "Operación":"Operations", "Consultando…":"Loading…", "↻ Actualizar":"↻ Refresh", "Fuente":"Source", "API interna":"Internal API", "Sin verificar":"Unverified", "Consulta":"Query", "Última actualización de registros":"Latest record update",
  "Cliente":"Customer", "Customer code exacto":"Exact customer code", "Tenant exacto":"Exact tenant", "Estado":"State", "Estado exacto":"Exact state", "Buscar identificador":"Search identifier", "Evento o referencia":"Event or reference", "Aplicar":"Apply", "Limpiar":"Clear",
  "No pudimos cargar los datos":"Unable to load data", "Reintentar":"Retry", "Consultando":"Loading", "Resultado de los filtros aplicados":"Results for the applied filters", "Estado actual · todos los registros":"Current state · all records", "Distribución por estado":"State distribution", "Filtrar":"Filter", "Sin estados registrados para esta consulta.":"No states recorded for this query.",
  "Registros":"Records", "página":"page", "Evento / ID":"Event / ID", "Referencia":"Reference", "Severidad":"Severity", "Resultado":"Outcome", "Actualizado":"Updated", "Datos de demostración":"Demonstration data", "Pendiente":"Pending", "No hay coincidencias":"No matches", "Aún no hay registros":"No records yet", "Ajusta los filtros para consultar otros registros.":"Adjust the filters to find other records.", "La fuente respondió correctamente. Los datos aparecerán cuando estén disponibles.":"The source responded successfully. Records will appear when available.",
  "Anterior":"Previous", "Siguiente":"Next", "registros":"records", "por página":"per page", "Revisión operativa":"Operational checklist", "Guía de revisión; no representa verificaciones automáticas.":"Review guide; these are not automated checks.", "Dashboard no encontrado":"Dashboard not found", "Volver a eventos":"Back to events", "Ir al contenido":"Skip to content", "Centro de operaciones":"Operations center", "Consulta operativa":"Operational queries", "Dashboards operativos":"Operational dashboards", "Sólo lectura · V1":"Read only · V1",
  "La consulta superó el tiempo de espera. Intenta actualizar.":"The request timed out. Try refreshing.", "No se pudo consultar el dashboard.":"Unable to query the dashboard.", "Respuesta inválida: el contrato del dashboard no coincide.":"Invalid response: dashboard contract mismatch.", "API de dashboards no conectada.":"Dashboard API is not connected.", "Revisa los filtros de la consulta.":"Check the query filters.", "Fuente no disponible. Verifica la conexión con el administrador.":"Data source unavailable. Ask your administrator to check the connection.",
  "Configuraciones de entrega":"Delivery configuration", "Filtros registrados y acciones por destino, APPLID y severidad.":"Registered filters and actions by destination, APPLID and severity.", "Todos":"All", "Todos los APPLID":"All APPLIDs", "Cualquier APPLID":"Any APPLID", "Todas las severidades":"All severities", "Cualquier severidad":"Any severity", "Todos los estados":"All states", "Habilitado":"Enabled", "Deshabilitado":"Disabled", "Auditoría":"Audit", "Filtros registrados":"Registered filters", "APPLID específicos":"Specific APPLIDs", "Destinos configurados":"Configured destinations", "Por APPLID":"By APPLID", "Por severidad":"By severity", "Selección actual":"Current selection", "Quitar selección":"Clear selection", "Nombre o ID del filtro":"Filter name or ID", "Criterios":"Criteria", "Peso":"Weight", "Destinos y acciones":"Destinations and actions", "Nombre":"Name", "Origen":"Origin", "Detalle de configuración":"Configuration detail", "Cerrar":"Close", "Todos los valores":"Any value", "Habilitar":"Enable", "Forzar apagado":"Force off", "Superponer":"Overlay", "Grupo":"Group", "Demora (segundos)":"Delay (seconds)", "Depende de Ticketing":"Depends on Ticketing", "Sí":"Yes", "No":"No", "Sin acciones configuradas":"No actions configured", "Global (C00)":"Global (C00)", "Los conteos representan filtros, no eventos entregados. Un filtro puede incluir varios destinos y severidades.":"Counts represent filters, not delivered events. A filter can cover multiple destinations and severities.", "Sin distribución para esta selección.":"No distribution for this selection.", "Sin condiciones adicionales":"No additional conditions", "Error de contrato Delivery.":"Delivery contract error.", "Crítica":"Critical", "Mayor":"Major", "Menor":"Minor", "Advertencia":"Warning", "Indeterminada":"Indeterminate", "Limpio":"Clear", "Filtros de demostración; no ejecutan acciones.":"Demo filters; they do not execute actions.", "Cambiar idioma":"Change language"
};

const I18n = createContext({language:"es" as Language, setLanguage:(_language:Language)=>{}, locale:"es-MX", t:(text:string)=>text});
export function I18nProvider({children}:{children:ReactNode}) {
  const [language,setLanguage] = useState<Language>(()=>{
    try { return localStorage.getItem("oem.language") === "en" ? "en" : "es"; } catch { return "es"; }
  });
  useEffect(()=>{document.documentElement.lang=language; document.title=language === "en" ? "OEM · Operational dashboards" : "OEM · Dashboards operativos"; try {localStorage.setItem("oem.language",language);} catch {/* storage may be unavailable */}},[language]);
  return <I18n.Provider value={{language,setLanguage,locale:language === "en" ? "en-US" : "es-MX",t:text=>language === "en" ? english[text] ?? text : text}}>{children}</I18n.Provider>;
}
export const useI18n = ()=>useContext(I18n);
export function LanguageSelector() {
  const {language,setLanguage,t}=useI18n();
  return <select aria-label={t("Cambiar idioma")} value={language} onChange={e=>setLanguage(e.target.value as Language)}><option value="es">Español</option><option value="en">English</option></select>;
}
