import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {useEssRequest} from './useEssRequest';
import {displayDate,errorMessage,essPath,eventType,parseConfig,parseEvent,parseEvents,parseHistory,parseQuarantine,type EssError,type EventState} from './ess.adapter';
import '../catalog/catalog.css';
import './ess.css';
function ErrorNotice({error,retry}:{error:EssError;retry:()=>void}){const {t}=useI18n();return <div className="catalog-error" role="alert"><strong>{t(errorMessage(error))}</strong><span>HTTP {error.status}</span><button onClick={retry}>{t('Reintentar')}</button></div>;}
export function EssAdminPage(){const {t}=useI18n();const [refresh,setRefresh]=useState(0),[tenant,setTenant]=useState(''),[mode,setMode]=useState<'events'|'quarantine'>('events');const config=useEssRequest('/api/ess/config',parseConfig,refresh);const selected=config.data?.tenants.includes(tenant)?tenant:config.data?.tenants[0]||'';
 return <section className="page catalog-page ess-page"><div className="page-heading"><div><span className="eyebrow">{t('Administración')} · Event State Service</span><h1>{t('Estado de eventos · ESS')}</h1><p>{t('Estado consolidado, referencias de integración e historial de transiciones.')}</p></div><Link className="admin-button" to="/administration">{t('Volver a Administración')}</Link></div>
 {config.loading&&<p role="status">{t('Cargando configuración ESS…')}</p>}{config.error&&<ErrorNotice error={config.error} retry={()=>setRefresh(x=>x+1)}/>}
 {config.data&&<><div className="ess-modes" role="group" aria-label={t('Alcance de consulta')}><button aria-pressed={mode==='events'} onClick={()=>setMode('events')}>{t('Eventos por tenant')}</button>{config.data.operatorQuarantine&&<button aria-pressed={mode==='quarantine'} onClick={()=>setMode('quarantine')}>{t('Cuarentena global · Operador')}</button>}</div>
 {mode==='events'?<><div className="ess-tenant"><label>{t('Tenant autorizado')}<select aria-label={t('Tenant autorizado')} value={selected} onChange={e=>setTenant(e.target.value)}>{config.data.tenants.map(x=><option key={x}>{x}</option>)}</select></label><span>{t('Solo lectura · PostgreSQL mediante ESS')}</span></div>{selected&&<TenantEvents key={selected} tenant={selected}/>}</>:config.data.operatorQuarantine&&<QuarantineSummary/>}</>}
 </section>;
}
function TenantEvents({tenant}:{tenant:string}){
 const {t,locale}=useI18n();const [limit,setLimit]=useState(25),[cursors,setCursors]=useState<string[]>(['']),[refresh,setRefresh]=useState(0),[lookup,setLookup]=useState(''),[selected,setSelected]=useState<string|null>(null);const cursor=cursors[cursors.length-1];const result=useEssRequest(essPath('events',{tenant,limit,after:cursor}),parseEvents,refresh);
 function open(event:FormEvent){event.preventDefault();if(lookup.trim())setSelected(lookup);}
 return <><div className="ess-toolbar"><form onSubmit={open}><label htmlFor="ess-event-key">{t('Consultar clave de evento')}</label><div><input id="ess-event-key" required maxLength={128} value={lookup} onChange={e=>setLookup(e.target.value)} placeholder={t('Clave exacta, incluida correlation:…')}/><button>{t('Consultar')}</button></div></form><label>{t('Por página')}<select value={limit} onChange={e=>{setLimit(Number(e.target.value));setCursors(['']);}}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><button onClick={()=>{setCursors(['']);setRefresh(x=>x+1);}} disabled={result.loading}>{t('Actualizar')}</button></div>
 {result.error&&<ErrorNotice error={result.error} retry={()=>setRefresh(x=>x+1)}/>}
 <div className="catalog-table-wrap" aria-busy={result.loading}><table><caption className="ess-caption">{t('Eventos del tenant')} · {tenant}</caption><thead><tr>{['Identidad','Tipo','Estado del evento','Ticket SNOW','Confirmaciones de proveedores','Tally','Versión','Última actualización','Detalle'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{result.data?.items.map(row=><tr key={row.event_key}><td><strong className="ess-key">{row.event_key}</strong><small>{row.event_id||'—'}</small></td><td>{t(eventType(row.event_key))}</td><td><span className="ess-state">{row.lifecycle_status||'—'}</span></td><td>{row.ticket_number||'—'}</td><td><ProviderStates row={row}/></td><td>{row.tally??'—'}</td><td>{row.version??'—'}</td><td>{displayDate(row.last_updated_at,locale)}</td><td><button onClick={()=>setSelected(row.event_key)} aria-label={`${t('Ver detalle de')} ${row.event_key}`}>{t('Detalle')}</button></td></tr>)}</tbody></table>{result.loading?<p role="status">{t('Consultando ESS…')}</p>:result.data?.items.length===0&&<div className="ess-empty"><h2>{t('Sin eventos para este tenant')}</h2><p>{t('ESS no devolvió eventos para esta consulta.')}</p></div>}</div>
 <div className="ess-pagination"><span>{t('Página')} {cursors.length} · {result.data?.items.length??'—'} {t('eventos en esta página')}</span><button disabled={result.loading||cursors.length===1} onClick={()=>setCursors(v=>v.slice(0,-1))}>{t('Anterior')}</button><button disabled={result.loading||!result.data?.nextCursor} onClick={()=>{if(result.data?.nextCursor)setCursors(v=>[...v,result.data!.nextCursor]);}}>{t('Siguiente')}</button></div><p className="ess-note">{t('Tally es el contador del evento, no el número de tickets. La lista puede cambiar mientras llegan actualizaciones.')}</p>
 {selected&&<EventDetail key={selected} tenant={tenant} eventKey={selected} close={()=>setSelected(null)}/>}</>;
}
function ProviderStates({row}:{row:EventState}){return <div className="ess-providers"><span>SNOW: {row.servicenow_status||'—'}</span><span>GNM: {row.gnm_status||'—'}</span><span>CACF: {row.cacf_status||'—'}</span></div>;}
function EventDetail({tenant,eventKey,close}:{tenant:string;eventKey:string;close:()=>void}){
 const {t,locale}=useI18n();const dialog=useRef<HTMLDialogElement>(null);const [refresh,setRefresh]=useState(0);const result=useEssRequest(essPath('event',{tenant,eventKey}),parseEvent,refresh);
 useEffect(()=>{dialog.current?.showModal();},[]);
 const row=result.data;
 return <dialog ref={dialog} className="catalog-dialog ess-dialog" aria-labelledby="ess-detail-title" onClose={close}><div className="catalog-dialog-heading"><h2 id="ess-detail-title">{t('Detalle de estado ESS')}</h2><button onClick={()=>dialog.current?.close()}>{t('Cerrar')}</button></div><p className="ess-key">{eventKey}</p><div className="ess-detail-identity"><span>{tenant}</span><span>{t(eventType(eventKey))}</span></div>
 {result.loading&&<p role="status">{t('Consultando ESS…')}</p>}{result.error&&<ErrorNotice error={result.error} retry={()=>setRefresh(x=>x+1)}/>}
 {row&&<><div className="ess-state-summary"><div><small>{t('Estado del evento')}</small><strong>{row.lifecycle_status||'—'}</strong></div><div><small>{t('Confirmaciones de proveedores')}</small><ProviderStates row={row}/></div></div><p className="ess-note">{t('OPEN/CLOSED describe el evento. RESOLVED y las demás confirmaciones describen al proveedor.')}</p>
 <dl className="ess-details">{[['ID del evento',row.event_id],['Ticket SNOW',row.ticket_number],['Notificación GNM',row.notification_id],['Automatización CACF',row.automation_id],['Severidad de origen',row.source_severity],['Severidad efectiva',row.effective_severity],['Tally',row.tally],['Versión',row.version],['Primera recepción',displayDate(row.first_seen_at,locale)],['Última actualización',displayDate(row.last_updated_at,locale)],['Último cambio de estado',displayDate(row.last_state_at,locale)]].map(([label,value])=><div key={label}><dt>{t(String(label))}</dt><dd>{value??'—'}</dd></div>)}</dl><History tenant={tenant} eventKey={eventKey}/></>}
 </dialog>;
}
function History({tenant,eventKey}:{tenant:string;eventKey:string}){const {t,locale}=useI18n();const [versions,setVersions]=useState([0]),[refresh,setRefresh]=useState(0);const result=useEssRequest(essPath('history',{tenant,eventKey,afterVersion:versions[versions.length-1],limit:25}),parseHistory,refresh);
 return <section className="ess-history"><h3>{t('Historial de transiciones')}</h3><p className="ess-note">{t('Solo transiciones explícitas; no incluye todos los resultados de integración.')}</p>{result.error&&<ErrorNotice error={result.error} retry={()=>setRefresh(x=>x+1)}/>}<div className="catalog-table-wrap" aria-busy={result.loading}><table><thead><tr>{['Versión','Desde','Hacia','Transición','Ocurrida','Registrada','ID de mensaje'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{result.data?.items.map((r,i)=><tr key={r.message_id||String(i)}><td>{r.aggregate_version??'—'}</td><td>{r.from_status||'—'}</td><td>{r.to_status||'—'}</td><td>{r.transition_type||'—'}</td><td>{displayDate(r.occurred_at,locale)}</td><td>{displayDate(r.recorded_at,locale)}</td><td>{r.message_id||'—'}</td></tr>)}</tbody></table>{result.loading?<p role="status">{t('Cargando transiciones…')}</p>:result.data?.items.length===0&&<p>{t('Sin transiciones explícitas registradas.')}</p>}</div><div className="ess-pagination"><span>{t('Página')} {versions.length}</span><button disabled={result.loading||versions.length===1} onClick={()=>setVersions(v=>v.slice(0,-1))}>{t('Transiciones anteriores')}</button><button disabled={result.loading||!result.data?.nextVersion} onClick={()=>{if(result.data?.nextVersion)setVersions(v=>[...v,result.data!.nextVersion]);}}>{t('Siguientes transiciones')}</button></div></section>;
}
function QuarantineSummary(){const {t,locale}=useI18n();const [refresh,setRefresh]=useState(0);const result=useEssRequest('/api/ess/operator/quarantine',parseQuarantine,refresh);return <section className="ess-quarantine"><div className="ess-global-notice"><h2>{t('Cuarentena · Resumen global')}</h2><p>{t('Capacidad de operador. Incluye todos los tenants: los rechazos no tienen atribución fiable de tenant.')}</p><small>{t('Solo razones, conteos y última fecha. No se muestran mensajes rechazados.')}</small></div><button disabled={result.loading} onClick={()=>setRefresh(x=>x+1)}>{t('Actualizar resumen global')}</button>{result.error&&<ErrorNotice error={result.error} retry={()=>setRefresh(x=>x+1)}/>}<div className="catalog-table-wrap" aria-busy={result.loading}><table><thead><tr><th>{t('Razón')}</th><th>{t('Conteo')}</th><th>{t('Último registro')}</th></tr></thead><tbody>{result.data?.items.map(r=><tr key={r.reason}><td>{r.reason}</td><td>{r.count}</td><td>{displayDate(r.last_seen_at,locale)}</td></tr>)}</tbody></table>{result.loading?<p role="status">{t('Consultando ESS…')}</p>:result.data?.items.length===0&&<p>{t('No hay registros en cuarentena.')}</p>}</div></section>;}
