quarkus.application.name=enrichment-engine
quarkus.http.host=0.0.0.0
quarkus.http.port=8082
camel.main.startup-summary-level=verbose
quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.eventmanagement.enrichment".level=INFO
