import {createUuid} from '../../shared/utils/uuid';
import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {api,ApiError,errorText,instant,operation,validateRule,type Operation,type RecordState,type Rule} from './blackouts.api';
import '../catalog/catalog.css';import '../product/product.css';import './blackouts.css';
type Row={id:string;name:string;tenant:string;source:string;status?:string;active_version?:number;latest_version?:number;configuration?:Rule;[key:string]:unknown};
function stored(pendingKey:string):Operation|null{try{return JSON.parse(sessionStorage.getItem(pendingKey)||'null');}catch{return null;}}
function remember(op:Operation|null,pendingKey:string){if(op)sessionStorage.setItem(pendingKey,JSON.stringify(op));else sessionStorage.removeItem(pendingKey);}
const blank=(tenant:string,suppression=false,mode:'scheduled'|'immediate'|'recurring'='scheduled'):Rule=>({id:'',version:1,type:suppression?'SUPPRESSION':mode==='immediate'?'IMMEDIATE':mode==='recurring'?'RECURRING':'SCHEDULED',...(suppression?{source:'MANUAL',externalStatus:'ACTIVE'}:{}),enabled:true,scope:{customerCode:tenant},schedule:{timezone:'America/Mexico_City',validFrom:mode==='immediate'?new Date().toISOString():'',validTo:mode==='immediate'?undefined:'',...(mode==='recurring'?{recurrence:'FREQ=DAILY;INTERVAL=1'}:{})},priority:10,reason:'',metadata:{owner:'operations'}});
function Failure({error}:{error:unknown}){const {t}=useI18n();return error?<div role="alert" className="catalog-error">{t(errorText(error))} {error instanceof ApiError&&<small>HTTP {error.status} · {error.code}</small>}</div>:null;}
export function BlackoutsPage({suppression=false}:{suppression?:boolean}){
 const pendingKey=suppression?'console.suppression.pending':'console.blackouts.pending';
 const {t}=useI18n();const [pending,setPending]=useState<Operation|null>(()=>stored(pendingKey));const [tenant,setTenant]=useState(()=>stored(pendingKey)?.tenant??''),[input,setInput]=useState(()=>stored(pendingKey)?.tenant??''),[query,setQuery]=useState(''),[rows,setRows]=useState<Row[]>([]),[truncated,setTruncated]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState<unknown>(),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState<string|null>(()=>stored(pendingKey)?.ruleId??null),[mode,setMode]=useState<'scheduled'|'immediate'|'recurring'>('scheduled'),[generation,setGeneration]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[conflict,setConflict]=useState(false);const busyRef=useRef(false);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError(undefined);fetch('/api/catalog/views/'+(suppression?'auto-suppression':'blackouts'),{cache:'no-store',signal:abort.signal}).then(async r=>{if(!r.ok)throw new ApiError(r.status,'CATALOG_UNAVAILABLE');const data=await r.json();if(!Array.isArray(data.items))throw new ApiError(503,'INVALID_RESPONSE');if(!abort.signal.aborted){setRows(data.items);setTruncated(data.truncated===true);}}).catch(e=>{if(!abort.signal.aborted){setError(e);setRows([]);}}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[refresh,suppression]);
 async function execute(op:Operation){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError(undefined);setNotice('');try{remember(op,pendingKey);setPending(op);await api(op.tenant,op.path,JSON.parse(op.body),op);remember(null,pendingKey);setPending(null);setNotice(op.path==='/rules'?'Guardado, pendiente de activación. La versión activa anterior se conserva.':'Cambio confirmado por el servidor.');setSelected(op.ruleId);setGeneration(x=>x+1);setRefresh(x=>x+1);setConflict(false);}catch(e){setError(e);if(op.path.endsWith('/enable'))setNotice('Versión guardada; activación pendiente de confirmar.');if(e instanceof ApiError&&[400,404,409,413,422,428].includes(e.status)){remember(null,pendingKey);setPending(null);if(e.status===409)setConflict(true);}}finally{busyRef.current=false;setBusy(false);}}
 const locked=busy||!!pending;const filtered=rows.filter(r=>(!tenant||r.tenant===tenant)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
 return <section className="page catalog-page blackout-page"><div className="page-heading"><div><span className="eyebrow">Event Processor</span><h1>{suppression?'AutoSuppression':'Blackouts'}</h1><p>{t(suppression?'Administración manual de supresión automática.':'Administración manual de ventanas de mantenimiento.')}</p></div><button disabled={loading||locked} onClick={()=>setRefresh(x=>x+1)}>{t('Actualizar tabla')}</button></div>
 <div className="catalog-toolbar"><label>Tenant<input aria-label="Tenant" list="blackout-tenants" value={input} disabled={locked} onChange={e=>setInput(e.target.value)} placeholder={t('Todos los tenants')}/></label><datalist id="blackout-tenants">{[...new Set(rows.map(r=>r.tenant))].map(x=><option key={x} value={x}/>)}</datalist><button disabled={locked} onClick={()=>{setTenant(input.trim());setSelected(null);setMode('scheduled');setConflict(false);setError(undefined);setNotice('');}}>{t('Seleccionar tenant')}</button><input aria-label={t('Buscar en la tabla')} placeholder={t('Buscar en la tabla')} value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={!tenant||locked} onClick={()=>{setSelected('');setMode('scheduled');setGeneration(x=>x+1);setConflict(false);setNotice('');}}>{t(suppression?'Nueva supresión':'Nuevo blackout programado')}</button>{!suppression&&<><button className="admin-button primary" disabled={!tenant||locked} onClick={()=>{setSelected('');setMode('immediate');setGeneration(x=>x+1);setConflict(false);setNotice('');}}>{t('Nuevo blackout inmediato')}</button><button disabled={!tenant||locked} onClick={()=>{setSelected('');setMode('recurring');setGeneration(x=>x+1);setConflict(false);setNotice('');}}>{t('Nuevo blackout recurrente')}</button></>}</div>
 <p>{tenant?`${t('Tenant seleccionado')}: ${tenant}`:t('Todos los tenants: selecciona uno para escribir o simular.')}</p><p className="product-note">{t(suppression?'Origen y aprobación declarados localmente; no verificados por un proveedor. Solo ACTIVE/APPROVED son elegibles con alcance y ventana coincidentes.':'Las reglas del Processor controlan la ejecución. El catálogo anterior es solo consulta. Guardar no activa una versión.')}</p>
 <Failure error={error}/>{notice&&<p role="status" className="blackout-notice">{t(notice)}</p>}{pending&&<div className="blackout-notice" role="status"><p>{t('Operación pendiente de confirmar. Reintenta exactamente la misma solicitud antes de realizar otro cambio.')}</p><code>{pending.key}</code><button disabled={busy} onClick={()=>execute(pending)}>{t('Reintentar misma operación')}</button></div>}{conflict&&<p role="alert">{t('Tu borrador se conserva. Carga la revisión actual antes de preparar otra operación.')}</p>}
 {truncated&&<p role="status">{t('Se muestran los primeros 2000 registros.')}</p>}<div className="catalog-table-wrap" aria-busy={loading}><table><thead><tr>{['Nombre','Tenant','Estado','Versión activa','Última guardada','Fuente',...(suppression?['Origen declarado','Estado declarado']:[]),'Detalle'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.tenant+':'+r.source+':'+r.id}><td><strong>{r.name}</strong><small className="product-id">{r.id}</small></td><td>{r.tenant}</td><td>{r.source==='Event Processor'?t(r.status==='RETIRED'?'Retirado':r.status==='ENABLED'?'Activo':r.status==='CREATED'?'Guardado sin activar':'Desactivado'):t('Solo consulta')}</td><td>{r.active_version??'—'}</td><td>{r.latest_version??'—'}</td><td>{r.source}</td>{suppression&&<><td>{r.configuration?.source}</td><td>{r.configuration?.externalStatus}</td></>}<td>{r.source==='Event Processor'?<button disabled={!tenant||locked} aria-label={`${t(suppression?'Abrir supresión':'Abrir blackout')} ${r.id}`} onClick={()=>{setSelected(r.id);setGeneration(x=>x+1);setConflict(false);setNotice('');}}>{t('Abrir')}</button>:<details><summary>{t('Ver detalle')}</summary><pre>{JSON.stringify(r,null,2)}</pre></details>}</td></tr>)}</tbody></table>{loading?<p role="status">{t('Cargando…')}</p>:!filtered.length&&<p>{t('Sin registros')}</p>}</div>
 {tenant&&selected!==null&&<Editor suppression={suppression} mode={mode} key={tenant+':'+selected+':'+mode+':'+generation} tenant={tenant} id={selected} locked={locked} conflict={conflict} execute={execute} reconcile={()=>{setConflict(false);setGeneration(x=>x+1);}}/>}
 {tenant&&<Simulation suppression={suppression} key={tenant} tenant={tenant}/>}
 </section>;
}
function Editor({tenant,id,locked,conflict,execute,reconcile,suppression,mode}:{suppression:boolean;mode:'scheduled'|'immediate'|'recurring';tenant:string;id:string;locked:boolean;conflict:boolean;execute:(op:Operation)=>Promise<void>;reconcile:()=>void}){
 const {t}=useI18n();const [record,setRecord]=useState<RecordState>(),[rule,setRule]=useState<Rule>(()=>blank(tenant,suppression,mode)),[etag,setEtag]=useState('"0"'),[loading,setLoading]=useState(!!id),[error,setError]=useState<unknown>(),[reason,setReason]=useState(''),[confirmation,setConfirmation]=useState<Operation|null>(null),[validated,setValidated]=useState(false),[validating,setValidating]=useState(false),[active,setActive]=useState<Rule>();
 useEffect(()=>{if(!id)return;const abort=new AbortController();api<RecordState>(tenant,'/rules/'+encodeURIComponent(id),undefined,undefined,abort.signal).then(({data,etag})=>{if(abort.signal.aborted)return;if(!etag||!(suppression?['SUPPRESSION']:['SCHEDULED','IMMEDIATE','RECURRING']).includes(data.rule.type))throw new ApiError(422,'NOT_EDITABLE_BLACKOUT');setRecord(data);setRule({...data.rule,scope:{...data.rule.scope,customerCode:tenant},version:data.latestVersion+1});setEtag(etag);}).catch(e=>{if(!abort.signal.aborted)setError(e);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[tenant,id,suppression]);
 const disabled=locked||loading||!!id&&!record||record?.status==='RETIRED'||conflict||!!confirmation;
 function change(update:Partial<Rule>){setRule(r=>({...r,...update}));setValidated(false);setError(undefined);}
 function prepare(action:string){setError(undefined);try{if(!reason.trim()||reason.length>2048)throw new Error('Motivo de cambio obligatorio, máximo 2048 caracteres.');const value=action==='save'?validateRule(rule,tenant):record!.rule;const path=action==='save'?'/rules':'/rules/'+encodeURIComponent(id)+'/'+action;setConfirmation(operation(tenant,path,action==='save'?{rule:value,reason}:{version:action==='enable'?record!.latestVersion:record!.activeVersion??record!.latestVersion,reason},etag,rule.id));}catch(e){setError(e);}}
 async function validate(){setValidating(true);setError(undefined);try{await api(tenant,'/rules/validate',{rule:validateRule(rule,tenant)});setValidated(true);}catch(e){setError(e);}finally{setValidating(false);}}
 return <article className="blackout-editor"><h2>{t(suppression?(id?'Editar supresión':'Nueva supresión'):(id?'Editar blackout':'Nuevo blackout'))} {id}</h2><Failure error={error}/>{loading&&<p role="status">{t('Cargando…')}</p>}{record&&<p>{t('Estado')}: {record.status} · {t('Versión activa')}: {record.activeVersion??'—'} · {t('Última guardada')}: {record.latestVersion} · ETag {etag}</p>}
 {id&&<button disabled={locked||!!confirmation} onClick={reconcile}>{t('Cargar revisión actual y descartar borrador')}</button>}
 {rule.type==='RECURRING'&&<><label className="blackout-recurrence">{t('Tipo')}<input readOnly value="RECURRING"/></label><label className="blackout-recurrence">{t('Recurrencia')}<input disabled={disabled||validating} value={rule.schedule.recurrence??''} placeholder="FREQ=DAILY;INTERVAL=1" onChange={e=>change({schedule:{...rule.schedule,recurrence:e.target.value}})}/><small>{t('Usa FREQ=DAILY o WEEKLY; INTERVAL y BYDAY son opcionales.')}</small></label></>}
 {record?.activeVersion&&<button onClick={async()=>{try{const response=await api<RecordState>(tenant,'/rules/'+encodeURIComponent(id)+'?version='+record.activeVersion);setActive(response.data.rule);}catch(e){setError(e);}}}>{t('Consultar definición activa')}</button>}{active&&<details open><summary>{t('Definición activa')}</summary><pre>{JSON.stringify(active,null,2)}</pre></details>}
 <fieldset disabled={disabled||validating}><legend>{t('Nueva versión de la definición')}</legend><div className="blackout-fields"><label>ID<input aria-label={suppression?'Suppression ID':'Blackout ID'} value={rule.id} disabled={!!id} maxLength={128} onChange={e=>change({id:e.target.value})}/></label><label>{t('Tipo')}<select value={rule.type} onChange={e=>change({type:e.target.value as Rule['type']})}>{suppression?<option>SUPPRESSION</option>:<><option>SCHEDULED</option><option>IMMEDIATE</option></>}</select></label>{suppression&&<><label>{t('Origen declarado')}<select value={rule.source} onChange={e=>change({source:e.target.value as Rule['source']})}><option>MANUAL</option><option>MAINTENANCE</option><option>CHANGE</option></select></label><label>{t('Estado declarado')}<select value={rule.externalStatus} onChange={e=>change({externalStatus:e.target.value as Rule['externalStatus']})}><option>ACTIVE</option><option>APPROVED</option><option>CANCELLED</option><option>COMPLETED</option></select></label></>}<label>{t('Zona IANA')}<input value={rule.schedule.timezone} onChange={e=>change({schedule:{...rule.schedule,timezone:e.target.value}})}/></label><label>{t('Inicio ISO 8601')}<input placeholder="2026-09-10T18:00:00Z" value={rule.schedule.validFrom} onChange={e=>change({schedule:{...rule.schedule,validFrom:e.target.value}})}/></label><label>{t('Fin ISO 8601')}<input placeholder={rule.type==='IMMEDIATE'?t('Opcional'):'2026-09-10T19:00:00Z'} value={rule.schedule.validTo??''} onChange={e=>change({schedule:{...rule.schedule,validTo:e.target.value}})}/></label><label>{t('Prioridad')}<input type="number" value={rule.priority} onChange={e=>change({priority:Number(e.target.value)})}/></label>{['node','nodeAlias','component','instanceId','monitoringSolution'].map(field=><label key={field}>{field}<input value={rule.scope[field]??''} onChange={e=>{const scope={...rule.scope};if(e.target.value)scope[field]=e.target.value;else delete scope[field];change({scope});}}/></label>)}<label>{t(suppression?'Motivo de supresión':'Motivo del blackout')}<input value={rule.reason} onChange={e=>change({reason:e.target.value})}/></label><label>{t('Responsable')}<input value={rule.metadata.owner} onChange={e=>change({metadata:{...rule.metadata,owner:e.target.value}})}/></label><label>{t('Referencia externa')}<input value={rule.metadata.externalReference??''} onChange={e=>change({metadata:{...rule.metadata,externalReference:e.target.value||undefined}})}/></label></div>
 {suppression&&<p className="blackout-notice">{t('Guardar CANCELLED no detiene la versión APPROVED activa. Activa la nueva versión o usa Desactivar para detenerla.')}</p>}<label><input type="checkbox" checked={rule.enabled} onChange={e=>change({enabled:e.target.checked})}/>{t('Versión habilitable (no activa al guardar)')}</label><p>{t('Inicio incluido, fin excluido. Usa Z u offset explícito; no se interpretan horas locales ambiguas.')}</p><p>{Object.keys(rule.scope).filter(x=>x!=='customerCode').length?t('Todos los selectores deben coincidir exactamente.'):t('Alcance: todos los recursos del tenant seleccionado.')}</p>
 <label>{t('Motivo del cambio')}<textarea maxLength={2048} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="blackout-actions"><button disabled={validating} onClick={validate}>{t('Validar definición')}</button><button onClick={()=>prepare('save')}>{t('Guardar nueva versión')}</button>{record&&<><button disabled={!record.rule.enabled} onClick={()=>prepare('enable')}>{t('Activar última guardada')}</button><button onClick={()=>prepare('disable')}>{t('Desactivar')}</button><button onClick={()=>prepare('retire')}>{t('Retirar')}</button></>}</div></fieldset>
 {validated&&<p role="status">{t('Definición válida. Aún no está guardada.')}</p>}{record?.status==='RETIRED'&&<p>{t('Retirado: estado terminal. El historial se conserva.')}</p>}
 {confirmation&&<section className="blackout-confirm" aria-label={t('Confirmar operación')}><h3>{t('Confirmar operación')}</h3><p>Tenant: {tenant} · ID: {confirmation.ruleId} · If-Match: {confirmation.etag}</p><p>{confirmation.path.endsWith('/retire')?t('Retirar es terminal y bloquea la reactivación.'):confirmation.path==='/rules'?t('Guardar no activa. La versión activa anterior seguirá ejecutándose.'):t('Esta operación cambia el estado operativo de la regla guardada.')}</p><p>{Object.keys((confirmation.path==='/rules'?JSON.parse(confirmation.body).rule:record?.rule)?.scope??{}).filter(x=>x!=='customerCode').length?t('Alcance limitado por los selectores indicados.'):t('Alcance: todos los recursos del tenant seleccionado.')}</p><pre>{confirmation.body}</pre><button disabled={locked} onClick={()=>{const op=confirmation;setConfirmation(null);void execute(op);}}>{t('Confirmar envío')}</button><button disabled={locked} onClick={()=>setConfirmation(null)}>{t('Cancelar')}</button></section>}
 {record&&<History tenant={tenant} id={id}/>}
 <Simulation suppression={suppression} tenant={tenant} candidate={()=>validateRule(rule,tenant)}/>
 </article>;
}
export function History({tenant,id}:{tenant:string;id:string}){
 const {t}=useI18n();const [pages,setPages]=useState<number[]>([0]),[data,setData]=useState<{items:Record<string,unknown>[];next:number|null}>(),[error,setError]=useState<unknown>(),[retry,setRetry]=useState(0);const after=pages[pages.length-1];
 useEffect(()=>{const abort=new AbortController();setData(undefined);setError(undefined);api<{items:Record<string,unknown>[];next:number|null}>(tenant,'/rules/'+encodeURIComponent(id)+'/history?limit=50&after='+after,undefined,undefined,abort.signal).then(r=>{if(!abort.signal.aborted)setData(r.data);}).catch(e=>{if(!abort.signal.aborted)setError(e);});return()=>abort.abort();},[tenant,id,after,retry]);
 return <section><h3>{t('Historial de cambios')}</h3><Failure error={error}/>{error?<button onClick={()=>setRetry(x=>x+1)}>{t('Reintentar')}</button>:!data?<p>{t('Cargando…')}</p>:<><div className="catalog-table-wrap"><table><thead><tr>{['revision','version','status','actor','reason','createdAt','checksum'].map(x=><th key={x}>{t(({revision:'Revisión',version:'Versión',status:'Estado',actor:'Operador local',reason:'Motivo',createdAt:'Fecha',checksum:'Checksum'} as Record<string,string>)[x])}</th>)}</tr></thead><tbody>{data.items.map(row=><tr key={String(row.revision)}>{['revision','version','status','actor','reason','createdAt','checksum'].map(x=><td key={x}>{String(row[x]??'—')}</td>)}</tr>)}</tbody></table></div><button disabled={pages.length===1} onClick={()=>setPages(x=>x.slice(0,-1))}>{t('Anterior')}</button><button disabled={!data.next} onClick={()=>setPages(x=>[...x,data.next!])}>{t('Siguiente')}</button></>}</section>;
}
function Simulation({tenant,candidate,suppression=false}:{tenant:string;candidate?:()=>Rule;suppression?:boolean}){
 const {t}=useI18n();const [node,setNode]=useState('router-1'),[at,setAt]=useState(''),[action,setAction]=useState('OPEN'),[alias,setAlias]=useState(''),[component,setComponent]=useState(''),[instance,setInstance]=useState(''),[source,setSource]=useState(''),[result,setResult]=useState<Record<string,unknown>>(),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);const epoch=useRef(0);useEffect(()=>()=>{epoch.current++;},[]);
 async function run(){const token=++epoch.current;setBusy(true);setError(undefined);setResult(undefined);try{const time=instant(at);const event={schemaVersion:'1.1',eventId:createUuid(),eventKey:node,tenant:{code:tenant},resource:{name:node,...(alias?{address:alias}:{}),...(component?{component}:{})},...(instance?{condition:{instanceId:instance}}:{}),...(source?{source:{system:source}}:{}),summary:suppression?'AutoSuppression simulation':'Blackout simulation',lifecycleAction:action,effectiveSeverity:3,timestamps:{receivedAt:time}};const {data}=await api<Record<string,unknown>>(tenant,'/simulations',{event,evaluatedAt:time,...(candidate?{candidateRule:candidate()}:{})});if(token===epoch.current)setResult(data);}catch(e){if(token===epoch.current)setError(e);}finally{if(token===epoch.current)setBusy(false);}}
 return <section className="blackout-simulation"><h3>{t(candidate?'Simulación de borrador':'Simulación de reglas activas')}</h3><p>{t(candidate?'La candidata reemplaza las reglas activas en esta prueba, incluso si no es habilitable.':'Consulta las reglas activas del tenant. No modifica eventos ni integraciones.')}</p><fieldset disabled={busy}><div className="blackout-fields"><label>{t('Recurso de prueba')}<input value={node} onChange={e=>setNode(e.target.value)}/></label><label>{t('Instante de evaluación ISO')}<input placeholder="2026-09-10T18:30:00Z" value={at} onChange={e=>setAt(e.target.value)}/></label><label>lifecycleAction<select value={action} onChange={e=>setAction(e.target.value)}><option>OPEN</option><option>CLOSE</option></select></label>{[['nodeAlias',alias,setAlias],['component',component,setComponent],['instanceId',instance,setInstance],['monitoringSolution',source,setSource]].map(([label,value,set])=><label key={String(label)}>{String(label)}<input value={String(value)} onChange={e=>(set as (v:string)=>void)(e.target.value)}/></label>)}</div><button disabled={!node||!at} onClick={run}>{t(candidate?'Simular borrador':'Simular reglas activas')}</button></fieldset><Failure error={error}/>{busy&&<p role="status">{t('Simulando…')}</p>}{result&&<div role="status"><p>directive: <strong>{String(result.directive)}</strong> · {suppression?'AutoSuppression':'Blackout'}.match: <strong>{String((result.stages as {stage:string;match:string}[])?.find(s=>s.stage===(suppression?'AutoSuppression':'Blackout'))?.match??'—')}</strong></p><p>snapshotChecksum: {String(result.snapshotChecksum)}</p>{suppression&&<><p>{t('SUPPRESS_INTEGRATIONS conserva el evento, correlación, recuperación y auditoría.')}</p><pre aria-label="AutoSuppression evidence">{JSON.stringify((result.stages as Record<string,unknown>[])?.find(s=>s.stage==='AutoSuppression'),null,2)}</pre></>}<details><summary>{t('Etapas y evidencia')}</summary><pre>{JSON.stringify(result,null,2)}</pre></details></div>}</section>;
}
