import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {api,ApiError,operation,type Operation} from '../blackouts/blackouts.api';
import {History} from '../blackouts/BlackoutsPage';
import {InventoryError} from '../inventory/InventoryPage';
import {CorrelationSimulation} from './CorrelationSimulation';
import {matchFields,newRule,supported,validate,type Rule,type Registry,type Summary} from './correlation.model';
import '../catalog/catalog.css';import '../blackouts/blackouts.css';import '../inventory/inventory.css';
import './correlation.css';
const storage='console.correlation.pending';
function pendingOperation():Operation|null{try{return JSON.parse(sessionStorage.getItem(storage)||'null');}catch{return null;}}
export function CorrelationPage(){
 const {t}=useI18n();const [pending,setPending]=useState(pendingOperation),[tenant,setTenant]=useState(()=>pendingOperation()?.tenant??''),[input,setInput]=useState(()=>pendingOperation()?.tenant??''),[rows,setRows]=useState<Registry[]>([]),[progress,setProgress]=useState({pages:0,read:0}),[loading,setLoading]=useState(false),[readErrors,setReadErrors]=useState<string[]>([]),[query,setQuery]=useState(''),[revision,setRevision]=useState(0),[editorKey,setEditorKey]=useState(0),[selected,setSelected]=useState<string|null>(()=>pendingOperation()?.ruleId??null),[draft,setDraft]=useState<Rule|null>(null),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),[conflict,setConflict]=useState(false),[busy,setBusy]=useState(false);const lock=useRef(false);
 useEffect(()=>{const abort=new AbortController();setRows([]);setProgress({pages:0,read:0});setReadErrors([]);if(!tenant)return;setLoading(true);
  (async()=>{let cursor:string|number|undefined;let pages=0,read=0;const found:Registry[]=[];const errors:string[]=[];const visited=new Set<string>();
   try{do{const {data}=await api<{items:Summary[];next:string|number|null}>(tenant,'/rules?limit=50'+(cursor===undefined?'':'&after='+encodeURIComponent(cursor)),undefined,undefined,abort.signal);if(abort.signal.aborted)return;
    if(!Array.isArray(data.items))throw new ApiError(503,'INVALID_RESPONSE');
    for(let start=0;start<data.items.length;start+=4){await Promise.all(data.items.slice(start,start+4).map(async item=>{try{const {data:record}=await api<Registry>(tenant,'/rules/'+encodeURIComponent(item.id),undefined,undefined,abort.signal);if(record.rule?.strategy)found.push(record);}catch(e){if(!abort.signal.aborted)errors.push(`${item.id}: ${e instanceof ApiError?'HTTP '+e.status+' · '+e.code:String(e)}`);}finally{read++;}}));if(abort.signal.aborted)return;setRows([...found]);setReadErrors([...errors]);setProgress({pages:pages+1,read});}
    pages++;cursor=data.next??undefined;if(cursor!==undefined){if(visited.has(String(cursor)))throw new ApiError(503,'REPEATED_CURSOR');visited.add(String(cursor));}
   }while(cursor!==undefined&&!abort.signal.aborted);
   }catch(e){if(!abort.signal.aborted)setReadErrors([...errors,e instanceof ApiError?'HTTP '+e.status+' · '+e.code:String(e)]);}finally{if(!abort.signal.aborted){setLoading(false);setProgress({pages,read});}}
  })();return()=>abort.abort();
 },[tenant,revision]);
 async function execute(op:Operation){if(lock.current)return;lock.current=true;setBusy(true);setError(undefined);setNotice('');try{sessionStorage.setItem(storage,JSON.stringify(op));setPending(op);await api(op.tenant,op.path,JSON.parse(op.body),op);sessionStorage.removeItem(storage);setPending(null);setSelected(op.ruleId);setConflict(false);setEditorKey(x=>x+1);setRevision(x=>x+1);setNotice(op.path==='/rules'?'Guardado, pendiente de activación. La versión activa anterior se conserva.':'Cambio confirmado por el servidor.');}catch(e){setError(e);if(op.path.endsWith('/enable'))setNotice('Versión guardada; activación pendiente de confirmar.');if(e instanceof ApiError&&[400,404,409,413,422,428].includes(e.status)){sessionStorage.removeItem(storage);setPending(null);if(e.status===409)setConflict(true);}}finally{lock.current=false;setBusy(false);}}
 const locked=busy||!!pending;const activeCount=rows.filter(r=>r.status==='ENABLED').length;const enabledDrafts=rows.filter(r=>r.rule.enabled).length;const conflictCount=rows.filter(r=>r.status==='CONFLICT').length;
 return <section className="page catalog-page blackout-page"><div className="page-heading"><div><span className="eyebrow">Event Processor</span><h1>{t('Correlación')}</h1><p>{t('Reglas ATTRIBUTE / GROUP y simulación de ciclos.')}</p></div><button disabled={locked||loading||!tenant} onClick={()=>setRevision(x=>x+1)}>{t('Actualizar tabla')}</button></div>
 <div className="catalog-toolbar"><label>Tenant<input aria-label="Tenant" disabled={locked} value={input} onChange={e=>setInput(e.target.value)}/></label><button disabled={locked} onClick={()=>{setTenant(input.trim());setSelected(null);setDraft(null);setError(undefined);setConflict(false);setNotice('');}}>{t('Seleccionar tenant')}</button><input aria-label={t('Buscar en la tabla')} value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={!tenant||locked} onClick={()=>{setSelected('');setEditorKey(x=>x+1);setConflict(false);setNotice('');}}>{t('Nueva regla de correlación')}</button></div>
 <p>{tenant?`${t('Tenant seleccionado')}: ${tenant}`:t('Selecciona un tenant para consultar, escribir o simular.')}</p><p>{t('Máximo 8 reglas activas por tenant. Guardar no activa. Correlación no crea tickets: Routing decide los comandos.')}</p>
 {tenant&&<section className="correlation-summary" aria-label={t('Resumen de correlación')}><div><small>{t('Reglas activas')}</small><strong>{activeCount}</strong><span>{t('En ejecución')}</span></div><div><small>{t('Reglas guardadas')}</small><strong>{rows.length}</strong><span>{t('Última lectura')}</span></div><div><small>{t('Habilitables')}</small><strong>{enabledDrafts}</strong><span>{t('Disponibles para activar')}</span></div><div className={conflictCount?'has-warning':''}><small>{t('Conflictos')}</small><strong>{conflictCount}</strong><span>{t('Requieren revisión')}</span></div></section>}
 <InventoryError error={error}/>{notice&&<p role="status" className="blackout-notice">{t(notice)}</p>}{pending&&<div role="status"><p>{t('Operación pendiente de confirmar. Reintenta exactamente la misma solicitud antes de realizar otro cambio.')}</p><code>{pending.key}</code><button disabled={busy} onClick={()=>execute(pending)}>{t('Reintentar misma operación')}</button></div>}
 {tenant&&<section className="correlation-catalog" aria-labelledby="correlation-catalog-title"><div className="correlation-section-heading"><div><span className="eyebrow">{t('Configuración versionada')}</span><h2 id="correlation-catalog-title">{t('Reglas de correlación')}</h2></div><span>{t('Solo las reglas activas participan en el procesamiento.')}</span></div><p role="status">{t(loading?'Leyendo definiciones…':'Lectura finalizada')} · {t('Páginas')}: {progress.pages} · {t('Definiciones')}: {progress.read}</p>{readErrors.length>0&&<div role="alert"><strong>{t('Listado incompleto: corrige los errores y actualiza.')}</strong>{readErrors.map((e,i)=><p key={i}>{e}</p>)}</div>}<div className="catalog-table-wrap"><table><thead><tr>{['ID','Escenario','Estado','Versión activa','Última guardada','Estrategia','Detalle'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.id}><td>{r.id}</td><td>{r.rule.metadata.description||t('Sin descripción de escenario')}</td><td><span className={`correlation-status ${String(r.status).toLowerCase()}`}>{r.status}</span></td><td>{r.activeVersion??'—'}</td><td>{r.latestVersion}</td><td>{r.rule.strategy}</td><td><button aria-label={`${t('Abrir regla')} ${r.id}`} disabled={locked} onClick={()=>{setSelected(r.id);setEditorKey(x=>x+1);setConflict(false);setNotice('');}}>{t('Abrir')}</button></td></tr>)}</tbody></table></div>{!loading&&!rows.length&&!readErrors.length&&<p>{t('Sin registros')}</p>}</section>}
 {tenant&&selected!==null&&<Editor key={tenant+':'+selected+':'+editorKey} tenant={tenant} id={selected} locked={locked} conflict={conflict} onDraft={setDraft} execute={execute} reconcile={()=>{setConflict(false);setError(undefined);setEditorKey(x=>x+1);setRevision(x=>x+1);}}/>}
 <details><summary>{t('Cómo funcionan los ciclos')}</summary><p>{t('Tenant, ID lógico y campos/valores identifican el grupo. Versiones con claves equivalentes conservan el ciclo; cambiar campos cambia su identidad.')}</p><p>{t('Recuperar un miembro no resuelve los demás. Recuperar todos cierra el ciclo; otro OPEN crea un nuevo groupId.')}</p><p>{t('La ventana expira miembros al procesar eventos, con borde inferior incluido. La capacidad limita el historial del ciclo, no solo miembros activos.')}</p><p>{t('CANDIDATE_LIMIT produce DEAD_LETTER sin cambio parcial. Tardíos, empates y recuperaciones huérfanas tienen decisiones explícitas.')}</p><p>{t('Desactivar detiene la evaluación; no borra ni resuelve grupos existentes.')}</p></details>
 {tenant&&<><CorrelationSimulation key={tenant} tenant={tenant} draft={draft} revision={revision}/><Explain key={'explain:'+tenant} tenant={tenant}/></>}
 </section>;
}
function Editor({tenant,id,locked,conflict,onDraft,execute,reconcile}:{tenant:string;id:string;locked:boolean;conflict:boolean;onDraft:(r:Rule|null)=>void;execute:(o:Operation)=>Promise<void>;reconcile:()=>void}){
 const {t}=useI18n();const [rule,setRule]=useState<Rule>(newRule),[record,setRecord]=useState<Registry>(),[etag,setEtag]=useState('"0"'),[loading,setLoading]=useState(!!id),[error,setError]=useState<unknown>(),[reason,setReason]=useState(''),[confirmation,setConfirmation]=useState<Operation|null>(null),[valid,setValid]=useState(false),[validating,setValidating]=useState(false),[active,setActive]=useState<Rule>();
 useEffect(()=>{if(!id)return;const abort=new AbortController();api<Registry>(tenant,'/rules/'+encodeURIComponent(id),undefined,undefined,abort.signal).then(({data,etag})=>{if(abort.signal.aborted)return;if(!data.rule.strategy||!etag)throw new ApiError(422,'WRONG_RULE_TYPE');setRecord(data);setEtag(etag);setRule({...data.rule,version:data.latestVersion+1});}).catch(e=>{if(!abort.signal.aborted)setError(e);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[tenant,id]);
 useEffect(()=>{onDraft(loading||id&&!record||!supported(rule)?null:rule);return()=>onDraft(null);},[rule,loading,id,record,onDraft]);
 const blocked=locked||loading||!!id&&!record||conflict||record?.status==='RETIRED'||!!confirmation||validating;
 function change(r:Rule){setRule(r);setValid(false);setError(undefined);}
 async function check(){setValidating(true);setError(undefined);try{await api(tenant,'/rules/validate',{rule:validate(rule)});setValid(true);}catch(e){setError(e);}finally{setValidating(false);}}
 function prepare(action:string){try{setError(undefined);if(!reason.trim()||reason.length>2048)throw new Error('Motivo de cambio obligatorio, máximo 2048 caracteres.');const path=action==='save'?'/rules':'/rules/'+encodeURIComponent(id)+'/'+action;setConfirmation(operation(tenant,path,action==='save'?{rule:validate(rule),reason}:{version:action==='enable'?record!.latestVersion:record!.activeVersion??record!.latestVersion,reason},etag,rule.id));}catch(e){setError(e);}}
 return <article className="blackout-editor"><h2>{t('Regla de correlación')} · {id||t('Nuevo')}</h2><InventoryError error={error}/>{record&&<p>{t('Estado')}: {record.status} · {t('Versión activa')}: {record.activeVersion??'—'} · {t('Última guardada')}: {record.latestVersion} · ETag {etag}</p>}{id&&<button disabled={locked||!!confirmation} onClick={reconcile}>{t('Cargar revisión actual y descartar borrador')}</button>}{conflict&&<p role="alert">{t('Tu borrador se conserva. Carga la revisión actual antes de preparar otra operación.')}</p>}{record?.activeVersion&&<button onClick={async()=>{try{const {data}=await api<Registry>(tenant,'/rules/'+encodeURIComponent(id)+'?version='+record.activeVersion);setActive(data.rule);}catch(e){setError(e);}}}>{t('Consultar definición activa')}</button>}{active&&<details open><summary>{t('Definición activa')}</summary><pre>{JSON.stringify(active,null,2)}</pre></details>}
 {!supported(rule)?<><p>{t('Definición avanzada: solo consulta en este formulario.')}</p><pre>{JSON.stringify(rule,null,2)}</pre></>:<fieldset disabled={blocked}><legend>{t('Nueva versión de la definición')}</legend><div className="blackout-fields"><label>ID<input aria-label="Correlation ID" disabled={!!id} value={rule.id} onChange={e=>change({...rule,id:e.target.value})}/></label><label>{t('Prioridad')}<input type="number" value={rule.priority} onChange={e=>change({...rule,priority:Number(e.target.value)})}/></label><label>{t('Responsable')}<input value={rule.metadata.owner} onChange={e=>change({...rule,metadata:{...rule.metadata,owner:e.target.value}})}/></label><label>{t('Ventana en segundos')}<input type="number" min={1} max={86400} value={rule.candidateSelection.windowSeconds} onChange={e=>change({...rule,candidateSelection:{...rule.candidateSelection,windowSeconds:Number(e.target.value)}})}/></label><label>maxCandidates<input type="number" min={1} max={32} value={rule.candidateSelection.maxCandidates} onChange={e=>change({...rule,candidateSelection:{...rule.candidateSelection,maxCandidates:Number(e.target.value)}})}/></label></div><p>ATTRIBUTE · GROUP · activeOnly: true</p><h3>{t('Condición del recurso')}</h3><p>resource.node</p><label>{t('Operador')}<select value={rule.scope.operator} onChange={e=>change({...rule,scope:{field:'resource.node',operator:e.target.value,...(e.target.value==='EQ'?{value:''}:{})}})}><option>EXISTS</option><option>EQ</option></select></label>{rule.scope.operator==='EQ'&&<label>{t('Valor de condición')}<input value={rule.scope.value??''} onChange={e=>change({...rule,scope:{...rule.scope,value:e.target.value}})}/></label>}<h3>{t('Campos de agrupación')}</h3>{matchFields.map(f=><label className="inventory-check" key={f}><input type="checkbox" aria-label={f} checked={rule.match.fields.includes(f)} onChange={e=>change({...rule,match:{fields:e.target.checked?[...rule.match.fields,f]:rule.match.fields.filter(x=>x!==f)}})}/>{f}</label>)}<label className="inventory-check"><input type="checkbox" checked={rule.enabled} onChange={e=>change({...rule,enabled:e.target.checked})}/>{t('Versión habilitable (no activa al guardar)')}</label><button onClick={check}>{t('Validar definición')}</button></fieldset>}
 {valid&&<p role="status">{t('Definición válida. Aún no está guardada.')}</p>}<fieldset disabled={blocked}><legend>{t('Operaciones de la configuración')}</legend><label>{t('Motivo del cambio')}<textarea value={reason} maxLength={2048} onChange={e=>setReason(e.target.value)}/></label><div className="blackout-actions"><button disabled={!supported(rule)} onClick={()=>prepare('save')}>{t('Guardar nueva versión')}</button>{record&&<><button disabled={!record.rule.enabled} onClick={()=>prepare('enable')}>{t('Activar última guardada')}</button><button onClick={()=>prepare('disable')}>{t('Desactivar')}</button><button onClick={()=>prepare('retire')}>{t('Retirar')}</button></>}</div></fieldset>{record?.status==='RETIRED'&&<p>{t('Retirado: estado terminal. El historial se conserva.')}</p>}
 {confirmation&&<section className="blackout-confirm" aria-label={t('Confirmar operación')}><h3>{t('Confirmar operación')}</h3><p>Tenant: {tenant} · ID: {rule.id} · If-Match: {etag}</p><p>{t(confirmation.path==='/rules'?'Guardar no activa. La versión activa anterior seguirá ejecutándose.':confirmation.path.endsWith('/retire')?'Retirar es terminal y bloquea la reactivación.':'Esta operación cambia el estado operativo de la regla guardada.')}</p>{confirmation.path.endsWith('/disable')&&<p>{t('Desactivar detiene la evaluación; no borra ni resuelve grupos existentes.')}</p>}<pre>{confirmation.body}</pre><button disabled={locked} onClick={()=>{const op=confirmation;setConfirmation(null);void execute(op);}}>{t('Confirmar envío')}</button><button disabled={locked} onClick={()=>setConfirmation(null)}>{t('Cancelar')}</button></section>}{record&&<History tenant={tenant} id={id}/>}</article>;
}
function Explain({tenant}:{tenant:string}){const {t}=useI18n();const [id,setId]=useState(''),[result,setResult]=useState<unknown>(),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);return <article className="blackout-editor"><h2>{t('Evidencia de evento real')}</h2><label>processingId<input value={id} onChange={e=>setId(e.target.value)}/></label><button disabled={busy||!id.trim()} onClick={async()=>{setBusy(true);setError(undefined);setResult(undefined);try{const {data}=await api(tenant,'/explain/'+encodeURIComponent(id.trim()));setResult(data);}catch(e){setError(e);}finally{setBusy(false);}}}>{t('Consultar evidencia')}</button><InventoryError error={error}/>{result!==undefined&&<pre>{JSON.stringify(result,null,2)}</pre>}</article>;}
