import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {api} from '../blackouts/blackouts.api';
import {InventoryError} from '../inventory/InventoryPage';
import {eventsFor,exampleSequence,validate,type Rule,type SequenceRow} from './correlation.model';
type Decision={ruleId:string;ruleVersion:number;reason:string;candidateCount:number;changed:boolean;group:null|{groupId:string;cycle:number;revision:number;resolved:boolean;members:unknown}};
type Result={correlationSource:string;results:Array<{directive?:string;correlation?:{decisions?:Decision[]};[key:string]:unknown}>;[key:string]:unknown};
export function CorrelationSimulation({tenant,draft,revision}:{tenant:string;draft:Rule|null;revision:number}){
 const {t}=useI18n();const [rows,setRows]=useState<SequenceRow[]>(exampleSequence),[candidate,setCandidate]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[result,setResult]=useState<Result>(),[submitted,setSubmitted]=useState<{revision:number;mode:string}>();const request=useRef<AbortController>();
 useEffect(()=>()=>request.current?.abort(),[]);
 async function simulate(){if(request.current)return;const abort=new AbortController();request.current=abort;setBusy(true);setError(undefined);try{const body={events:eventsFor(rows,tenant),...(candidate?{candidateRules:[validate(draft!)]}:{})};const {data}=await api<Result>(tenant,'/simulations',body,undefined,abort.signal);if(!abort.signal.aborted){setResult(data);setSubmitted({revision,mode:candidate?'CANDIDATE':'ACTIVE'});}}catch(e){if(!abort.signal.aborted)setError(e);}finally{if(!abort.signal.aborted)setBusy(false);request.current=undefined;}}
 function change(i:number,patch:Partial<SequenceRow>){setRows(a=>a.map((r,n)=>n===i?{...r,...patch}:r));}
 return <article className="blackout-editor"><h2>{t('Simulación de secuencia')}</h2><p>{t('Cada simulación comienza vacía: no consulta ni modifica grupos reales, eventos ni outbox.')}</p><p>{t('La candidata reemplaza el snapshot completo; no se suma a las reglas activas.')}</p><fieldset disabled={busy}><label><input type="checkbox" checked={candidate} onChange={e=>setCandidate(e.target.checked)}/>{t('Usar solo el borrador como candidata')}</label><div className="catalog-table-wrap"><table><thead><tr>{['Miembro (eventKey)','Recurso','Acción','receivedAt ISO','Quitar'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><input aria-label={`eventKey ${i+1}`} value={r.key} onChange={e=>change(i,{key:e.target.value})}/></td><td><input aria-label={`resource ${i+1}`} value={r.node} onChange={e=>change(i,{node:e.target.value})}/></td><td><select aria-label={`action ${i+1}`} value={r.action} onChange={e=>change(i,{action:e.target.value as 'OPEN'|'CLOSE'})}><option>OPEN</option><option>CLOSE</option></select></td><td><input aria-label={`receivedAt ${i+1}`} value={r.at} onChange={e=>change(i,{at:e.target.value})}/></td><td><button aria-label={`${t('Quitar evento')} ${i+1}`} disabled={rows.length===1} onClick={()=>setRows(a=>a.filter((_,n)=>n!==i))}>−</button></td></tr>)}</tbody></table></div><button disabled={rows.length>=64} onClick={()=>setRows(a=>[...a,{key:'member-'+(a.length+1),node:'router-1',action:'OPEN',at:new Date().toISOString()}])}>{t('Agregar evento')}</button><button onClick={()=>setRows(exampleSequence())}>{t('Cargar ejemplo de ciclo')}</button><button disabled={candidate&&!draft} onClick={simulate}>{t('Simular secuencia')}</button></fieldset><InventoryError error={error}/>
 {result&&<section role="status"><p>{submitted?.mode} · {tenant} · correlationSource: <strong>{result.correlationSource}</strong></p>{submitted?.revision!==revision&&<p>{t('La configuración cambió desde esta consulta. Vuelve a simular para ver el estado actual.')}</p>}{result.results?.map((r,i)=><section key={i}><h3>{t('Evento')} {i+1} · {String(r.directive??'')}</h3>{r.correlation?.decisions?.length?r.correlation.decisions.map((d,n)=><div key={n}><p>{d.ruleId}:{d.ruleVersion} · {d.reason} · candidateCount: {d.candidateCount} · changed: {String(d.changed)}</p>{d.group?<><p>groupId: {d.group.groupId} · cycle: {d.group.cycle} · revision: {d.group.revision} · resolved: {String(d.group.resolved)}</p><pre>{JSON.stringify(d.group.members,null,2)}</pre></>:<p>group: null</p>}</div>):<p>{t('Sin decisiones de correlación')}</p>}</section>)}<details><summary>{t('Respuesta completa')}</summary><pre>{JSON.stringify(result,null,2)}</pre></details></section>}
 </article>;
}
