import {useEffect,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import kafkaLogo from '../../assets/apache-kafka.png';
import '../catalog/catalog.css';
import './product.css';
type Topic={name:string;label:string;flow:string;status:string;partitions:number|null;expectedPartitions:number|null;messages:number|null;replicationFactor:number|null;cleanupPolicy:string|null};
type Snapshot={cluster:string;status:string;brokers:number;observedAt:string;topics:Topic[]};
const statuses:Record<string,string>={healthy:'Disponible',missing:'No existe',drift:'Configuración diferente',error:'Réplicas incompletas'};
export function MiddlewarePage(){const {t,locale}=useI18n();const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');const timeout=setTimeout(()=>abort.abort(),30000);fetch('/api/administration/middleware',{signal:abort.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{if(!Array.isArray(d.topics))throw new Error();setData(d);}).catch(()=>{setData(null);setError('No se pudo consultar Kafka. Verifica el broker y Kafka UI.');}).finally(()=>{clearTimeout(timeout);setLoading(false);});return()=>{clearTimeout(timeout);abort.abort();};},[revision]);
 const filtered=data?.topics.filter(x=>(x.name+' '+x.label+' '+x.flow).toLowerCase().includes(query.toLowerCase()))||[];
 return <section className="page catalog-page product-page"><div className="page-heading"><div><span className="eyebrow">{t('Configuración del producto')} · Apache Kafka</span><h1>Middleware</h1><p>{t('Transporte de eventos, comandos, resultados y ciclo de vida del producto.')}</p></div><div className="kafka-logo"><img src={kafkaLogo} alt="Apache Kafka"/></div></div>
 <div className="product-actions"><a className="admin-button primary" href={`http://${window.location.hostname}:8085`} target="_blank" rel="noreferrer">{t('Administrar Kafka')} ↗</a><button onClick={()=>setRevision(r=>r+1)} disabled={loading}>{t('Actualizar')}</button><span>{data?data.cluster:'event-management-local'}</span></div>
 <div className="product-metrics"><article><span>{t('Clúster')}</span><strong>{loading?'…':error?t('Error'):data?.status}</strong></article><article><span>Brokers</span><strong>{data?.brokers??'—'}</strong></article><article><span>{t('Tópicos disponibles')}</span><strong>{data?.topics.filter(x=>x.status!=='missing').length??'—'}</strong></article><article><span>{t('Requieren atención')}</span><strong>{data?.topics.filter(x=>x.status!=='healthy').length??'—'}</strong></article></div>
 <div className="product-flow" aria-label={t('Flujo del producto')}>{['events.raw','integration.commands','integration.results','events.lifecycle','event.journal'].map(x=><button key={x} type="button" onClick={()=>setQuery(query===x?'':x)} aria-pressed={query===x}><code>{x}</code></button>)}</div>
 <p className="product-note">{t('Vista de tópicos y contrato del producto. Kafka UI permite configurar tópicos, retención, consumidores y brokers.')}</p>
 {error&&<div role="alert" className="catalog-error">{t(error)}</div>}{data?.topics.some(x=>x.status==='missing')&&<div className="catalog-error" role="alert">{t('Hay tópicos definidos por el producto que no existen en este clúster.')} {data.topics.filter(x=>x.status==='missing').map(x=>x.name).join(', ')}</div>}
 <div className="catalog-toolbar"><input aria-label={t('Buscar tópico')} placeholder={t('Buscar tópico')} value={query} onChange={e=>setQuery(e.target.value)}/><span>{data&&new Date(data.observedAt).toLocaleString(locale)}</span></div>
 <div className="catalog-table-wrap" aria-busy={loading}><table><thead><tr><th>{t('Tópico / función')}</th><th>{t('Flujo')}</th><th>{t('Estado')}</th><th>{t('Particiones')}</th><th>{t('Réplicas')}</th><th>{t('Mensajes')}</th><th>Cleanup</th></tr></thead><tbody>{filtered.map(x=><tr key={x.name}><td><code>{x.name}</code><small className="product-id">{t(x.label)}</small></td><td>{t(x.flow)}</td><td><span className={'product-status '+x.status}>{t(statuses[x.status]||x.status)}</span></td><td>{x.partitions??'—'}{x.status==='drift'&&` / ${x.expectedPartitions}`}</td><td>{x.replicationFactor??'—'}</td><td>{x.messages??'—'}</td><td>{x.cleanupPolicy??'—'}</td></tr>)}</tbody></table>{!loading&&!filtered.length&&<p>{t('Sin resultados')}</p>}</div></section>;
}
