import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import '../catalog/catalog.css';
import './product.css';
export type ProductKind='blackouts'|'inventory-services'|'policies'|'aiops-extensions'|'auto-suppression';
const labels:Record<ProductKind,[string,string]>={blackouts:['Blackouts','Ventanas de mantenimiento y reglas de exclusión.'],'inventory-services':['Inventory Services','Recursos y servicios de clientes registrados en el inventario.'],policies:['Policies','Políticas y reglas del producto por tenant.'],'aiops-extensions':['AIOps Extensions','Extensiones AIOps configuradas en Event Processor.'],'auto-suppression':['AutoSuppression','Reglas de supresión automática, alcance y programación.']};
type Item={id:string;name:string;tenant:string;enabled:boolean;source?:string;status?:string;[key:string]:unknown};
export function ProductCatalogPage({kind}:{kind:ProductKind}){
 const {t}=useI18n();const [rows,setRows]=useState<Item[]>([]),[query,setQuery]=useState(''),[tenant,setTenant]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[detail,setDetail]=useState<Item|null>(null),[truncated,setTruncated]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');fetch('/api/catalog/views/'+kind,{signal:abort.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{if(!Array.isArray(d.items))throw new Error();setRows(d.items);setTruncated(d.truncated);}).catch(()=>{if(!abort.signal.aborted){setError('No se pudo consultar PostgreSQL.');setRows([]);}}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[kind,revision]);
 useEffect(()=>{if(detail)dialog.current?.showModal();else dialog.current?.close();},[detail]);
 const filtered=rows.filter(r=>(!tenant||r.tenant===tenant)&&JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
 return <section className="page catalog-page product-page"><div className="page-heading"><div><span className="eyebrow">{t('Configuración del producto')} · PostgreSQL</span><h1>{labels[kind][0]}</h1><p>{t(labels[kind][1])}</p></div><button onClick={()=>setRevision(r=>r+1)} disabled={loading}>{t('Actualizar')}</button></div>
 <div className="product-metrics"><article><span>{t('Registros')}</span><strong>{error||loading?'—':rows.length}</strong></article><article><span>{t('Habilitados')}</span><strong>{error||loading?'—':rows.filter(x=>x.enabled).length}</strong></article><article><span>Tenants</span><strong>{error||loading?'—':new Set(rows.map(x=>x.tenant)).size}</strong></article></div>
 <p className="product-note">{t('Vista de consulta. Las reglas del motor se publican mediante su API de administración.')}</p>{kind==='inventory-services'&&<p className="product-note">{t('Este inventario contiene recursos de clientes; los contenedores de la plataforma están en Administración.')}</p>}
 {error&&<div role="alert" className="catalog-error">{t(error)}</div>}{truncated&&<div role="status">{t('Se muestran los primeros 2000 registros.')}</div>}
 <div className="catalog-toolbar"><input type="search" aria-label={t('Buscar en la tabla')} placeholder={t('Buscar en la tabla')} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Tenant" value={tenant} onChange={e=>setTenant(e.target.value)}><option value="">{t('Todos los tenants')}</option>{[...new Set(rows.map(x=>x.tenant))].map(x=><option key={x}>{x}</option>)}</select><span>{filtered.length} {t('resultados')}</span></div>
 <div className="catalog-table-wrap" aria-busy={loading}><table><thead><tr><th>{t('Nombre')}</th><th>Tenant</th><th>{t('Estado')}</th><th>{t('Fuente')}</th><th>{t('Detalle')}</th></tr></thead><tbody>{filtered.map(r=><tr key={r.tenant+':'+r.id+':'+r.source}><td><strong>{r.name}</strong><small className="product-id">{r.id}</small></td><td>{r.tenant}</td><td>{t(r.enabled?'Habilitado':'Deshabilitado')}</td><td>{r.source|| (kind==='inventory-services'?'PostgreSQL':'Event Processor')}</td><td><button onClick={()=>setDetail(r)}>{t('Ver detalle')}</button></td></tr>)}</tbody></table>{loading?<p role="status">{t('Cargando…')}</p>:!filtered.length&&<div className="product-empty"><h2>{t('Sin registros')}</h2><p>{t(error?'No hay datos disponibles mientras la conexión esté fallando.':'No hay configuraciones que coincidan con esta vista. No se muestran datos simulados.')}</p></div>}</div>
 <dialog ref={dialog} className="catalog-dialog" aria-label={t('Detalle')} onCancel={()=>setDetail(null)} onClose={()=>setDetail(null)}>{detail&&<><div className="catalog-dialog-heading"><h2>{detail.name}</h2><button onClick={()=>setDetail(null)}>{t('Cerrar')}</button></div><pre className="product-json">{JSON.stringify(detail,null,2)}</pre></>}</dialog></section>;
}
