import { useEffect, useRef, useState, type FormEvent } from 'react';
import { useI18n } from '../../shared/i18n/I18nProvider';
import './catalog.css';
type Target={target:string;behavior:string;assignmentGroup:string|null;actionReference:string|null;delaySeconds:number|null;dependsOnTicketing:boolean};
type Customer={customer_code:string;customer:string;bamid:string;gnmorgid:string;snow_company_id:string;snow_assignment_group:string;gnm_assignment_group:string;cacf_assignment_group:string;chatops_team:string;aiops_extension:string;timezone:string;enabled:boolean;origin?:string;updated_at?:string};
type Filter={filter_id?:string;name:string;description:string;customer_code:string;applid:string|null;filter_state:number;filter_weight:number;severities:number[]|null;criteria:Record<string,{operator:string;value:string|number|boolean}>;targets:Target[];origin?:string;updated_at?:string};
type Row=Customer|Filter;
const destinations=[['gnm','GNM'],['snow','SNOW'],['glpi','GLPI'],['cacf','CACF'],['chatops','ChatOps'],['extensions','AIOps Extension']];
const customerLabels:Record<string,string>={customer:'Cliente',customer_code:'Customer code',bamid:'BAM ID',gnmorgid:'GNM Org ID',snow_company_id:'SNOW Company ID',gnm_assignment_group:'Grupo GNM',snow_assignment_group:'Grupo SNOW',cacf_assignment_group:'Grupo CACF',chatops_team:'Teams de ChatOps',aiops_extension:'AIOps Extension',timezone:'Zona horaria'};
const fields=['IBMManaged','ResourceId','Service','SubAccount','Subsystem','Application','InstanceId','SubComponent','Component','ComponentType','ResourceUsage','OSType','MsgId','AlertKey','AlertGroup','ResourceType','EventType','MonitoringSolution','Location','SourceType','OutsideServiceHours'];
const emptyCustomer=():Customer=>({customer:'',customer_code:'',bamid:'',gnmorgid:'',snow_company_id:'',gnm_assignment_group:'',snow_assignment_group:'',cacf_assignment_group:'',chatops_team:'',aiops_extension:'',timezone:'America/Mexico_City',enabled:true});
const emptyFilter=():Filter=>({name:'',description:'',customer_code:'',applid:null,filter_state:1,filter_weight:0,severities:null,criteria:{},targets:[]});
const errors:Record<string,string>={database_unavailable:'PostgreSQL no disponible. No se guardaron cambios.',stale_record:'Este registro cambió. Cierra y actualiza la tabla antes de editar.',customer_in_use:'El cliente tiene filtros asociados. Reasígnalos antes de eliminarlo.',already_exists:'Ya existe ese customer code.',required_destination:'Completa el grupo, Teams o referencia de cada destino.',invalid_timezone:'Zona horaria inválida.',customer_not_found:'Selecciona un cliente existente.',invalid_criteria:'Revisa los criterios y sus valores.',narrow_search:'Hay demasiados resultados. Acota la búsqueda.'};
async function api(path:string,method='GET',body?:unknown){const response=await fetch('/api/catalog/'+path,{method,headers:method==='GET'?{}:{'Content-Type':'application/json','X-Console-Action':'1'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)}); const result=await response.json().catch(()=>({error:'unavailable'})); if(!response.ok)throw new Error(errors[result.error]??'No se pudo completar la operación. Revisa la conexión y los datos.'); return result;}
export function CatalogPage({kind}:{kind:'filters'|'customers'}){
 const {t}=useI18n();const isFilter=kind==='filters';
 const [rows,setRows]=useState<Row[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[query,setQuery]=useState(''),[activeQuery,setActiveQuery]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[draft,setDraft]=useState<Row|null>(null),[deleting,setDeleting]=useState(false);
 const defaultColumns=isFilter?['name','customer_code','filter_state','targets','origin']:['customer','customer_code','bamid','gnmorgid','enabled'];
 const [columns,setColumns]=useState<string[]>(()=>{try{const saved:unknown=JSON.parse(localStorage.getItem('catalog.columns.'+kind)||'null');return Array.isArray(saved)&&saved.length&&saved.every(x=>typeof x==='string')?[...new Set(saved)] as string[]:defaultColumns;}catch{return defaultColumns;}});
 const dialog=useRef<HTMLDialogElement>(null);const generation=useRef(0);
 async function refresh(search=activeQuery){const current=++generation.current;setLoading(true);setError('');try{const [result,cs]=await Promise.all([api(kind+'?q='+encodeURIComponent(search)),isFilter?api('customers'):Promise.resolve(null)]);if(current!==generation.current)return;setRows(result.items);if(cs)setCustomers(cs.items);}catch(e){if(current===generation.current)setError((e as Error).message);}finally{if(current===generation.current)setLoading(false);}}
 useEffect(()=>{void refresh();return()=>{generation.current++;};},[kind]);
 useEffect(()=>{if(draft)dialog.current?.showModal();else dialog.current?.close();},[draft!==null]);
 const allColumns=isFilter?{name:'Nombre',customer_code:'Cliente',applid:'APPLID',filter_state:'Estado',filter_weight:'Peso',targets:'Destinos',gnm:'Grupo GNM',snow:'Grupo SNOW',glpi:'Grupo GLPI (ID)',cacf:'Grupo CACF',chatops:'Teams de ChatOps',extensions:'AIOps Extension',criteria:'Criterios',origin:'Origen'}:{...customerLabels,enabled:'Estado',origin:'Origen'};
 function toggleColumn(key:string){const next=columns.includes(key)?columns.filter(x=>x!==key):[...columns,key];if(!next.length)return;setColumns(next);try{localStorage.setItem('catalog.columns.'+kind,JSON.stringify(next));}catch{/* optional view preference */}}
 function open(row:Row){setError('');setMessage('');setDeleting(false);setDraft(structuredClone(row));}
 function change(key:string,value:unknown){setDraft(old=>old?{...old,[key]:value}:old);}
 async function save(event:FormEvent){event.preventDefault();if(!draft)return;setBusy(true);setError('');try{const key=isFilter?(draft as Filter).filter_id:(draft as Customer).customer_code;await api(kind+(draft.updated_at?'/'+encodeURIComponent(key!):''),draft.updated_at?'PUT':'POST',draft);setDraft(null);setMessage('Guardado en PostgreSQL.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!draft)return;setBusy(true);setError('');try{const key=isFilter?(draft as Filter).filter_id:(draft as Customer).customer_code;await api(kind+'/'+encodeURIComponent(key!),'DELETE',{updated_at:draft.updated_at});setDraft(null);setMessage('Registro eliminado de PostgreSQL.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function cell(row:Row,key:string){const v=(row as unknown as Record<string,unknown>)[key];if(key==='filter_state')return t(['Habilitado','Deshabilitado','Auditoría'][v as number]);if(key==='enabled')return t(v?'Habilitado':'Deshabilitado');if(destinations.some(d=>d[0]===key)){const target=(row as Filter).targets.find(x=>x.target===key);return target?(key==='extensions'?target.actionReference:target.assignmentGroup)||'—':'—';}if(key==='targets')return <div className="catalog-tags">{(v as Target[]).map(x=><span key={x.target} title={`${destinations.find(d=>d[0]===x.target)?.[1]}: ${x.assignmentGroup||x.actionReference||'—'}`}><span className="admin-sr">{x.assignmentGroup||x.actionReference} · </span>{destinations.find(d=>d[0]===x.target)?.[1]}{x.dependsOnTicketing?' ⏳':''}{x.behavior==='force_off'?' · '+t('Deshabilitado'):''}</span>)}</div>;if(key==='criteria')return Object.entries((row as Filter).criteria).map(([f,c])=>`${f} ${c.operator} ${c.value}`).join(' · ')||t('Todos');if(key==='origin')return t(v==='demo'?'Demostración':String(v||'manual'));return String(v??'—')||'—';}
 const f=draft as Filter,c=draft as Customer;
 function patchTarget(target:string,patch:Partial<Target>){change('targets',f.targets.map(x=>x.target===target?{...x,...patch}:x));}
 function enableTarget(target:string,enabled:boolean){const customer=customers.find(x=>x.customer_code===f.customer_code);const group=customer?(customer as unknown as Record<string,string>)[target==='chatops'?'chatops_team':target+'_assignment_group']:'';change('targets',enabled?[...f.targets,{target,behavior:'enable',assignmentGroup:group||'',actionReference:target==='extensions'?customer?.aiops_extension||'':'',delaySeconds:null,dependsOnTicketing:false}]:f.targets.filter(x=>x.target!==target));}
 return <section className="page catalog-page"><div className="page-heading"><div><span className="eyebrow">{t('Administración')} · PostgreSQL</span><h1>{t(isFilter?'Criterios y Filtros':'Cliente')}</h1><p>{t(isFilter?'Configura criterios, destinos y dependencias por cliente.':'Identidad y configuración de integración de cada customer.')}</p></div><button className="catalog-primary" onClick={()=>open(isFilter?emptyFilter():emptyCustomer())} disabled={loading||!!error}>{t(isFilter?'Nuevo filtro':'Nuevo cliente')}</button></div>
 <div className="catalog-summary"><strong>{rows.length}</strong> {t(isFilter?'filtros en la vista':'clientes en la vista')}<span>{t('Catálogo PostgreSQL')}</span></div>
 {isFilter&&<p className="catalog-note">{t('Guardar configura el catálogo; la ejecución de integraciones depende del motor de enrutamiento. Los ejemplos usan destinos ficticios.')} ⏳ {t('Esperar al ticket')}</p>}
 {!draft&&error&&<div role="alert" className="catalog-error">{t(error)}</div>}{message&&<div role="status">{t(message)}</div>}
 <div className="catalog-toolbar"><form onSubmit={e=>{e.preventDefault();setActiveQuery(query);void refresh(query);}}><input aria-label={t('Buscar en la tabla')} placeholder={t('Buscar en la tabla')} value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={loading}>{t('Buscar')}</button></form><button onClick={()=>void refresh()} disabled={loading}>{t('Actualizar')}</button><details><summary>{t('Columnas visibles')}</summary><div className="catalog-columns">{Object.entries(allColumns).map(([key,label])=><label key={key}><input type="checkbox" checked={columns.includes(key)} onChange={()=>toggleColumn(key)}/>{t(label)}</label>)}</div></details></div>
 <div className="catalog-table-wrap" aria-busy={loading}><table><thead><tr>{columns.map(key=><th key={key}>{t(allColumns[key as keyof typeof allColumns]||key)}</th>)}<th>{t('Acciones')}</th></tr></thead><tbody>{rows.map(row=><tr key={(row as Filter).filter_id||(row as Customer).customer_code}>{columns.map(key=><td key={key}>{cell(row,key)}</td>)}<td><button disabled={loading||!!error} onClick={()=>open(row)}>{t('Editar')}</button></td></tr>)}</tbody></table>{loading?<p role="status">{t('Cargando…')}</p>:!rows.length&&<p>{t('Sin resultados')}</p>}</div>
 <dialog ref={dialog} className="catalog-dialog" aria-labelledby="catalog-dialog-title" onCancel={e=>{if(busy)e.preventDefault();else setDraft(null);}} onClose={()=>{if(!busy)setDraft(null);}}>{draft&&<form onSubmit={save}><div className="catalog-dialog-heading"><h2 id="catalog-dialog-title">{t(isFilter?(draft.updated_at?'Editar filtro':'Nuevo filtro'):(draft.updated_at?'Editar cliente':'Nuevo cliente'))}</h2><button type="button" disabled={busy} onClick={()=>setDraft(null)} aria-label={t('Cerrar')}>×</button></div>{error&&<div className="catalog-error" role="alert">{t(error)}</div>}<fieldset disabled={busy} className="catalog-fields">
 {isFilter?<><div className="catalog-grid"><label>{t('Nombre')}<input required maxLength={200} value={f.name} onChange={e=>change('name',e.target.value)}/></label><label>{t('Cliente')}<select required value={f.customer_code} onChange={e=>change('customer_code',e.target.value)}><option value="">{t('Selecciona un cliente')}</option>{customers.map(x=><option key={x.customer_code} value={x.customer_code}>{x.customer} · {x.customer_code}</option>)}</select></label><label>APPLID<input maxLength={128} value={f.applid||''} onChange={e=>change('applid',e.target.value||null)}/></label><label>{t('Estado')}<select value={f.filter_state} onChange={e=>change('filter_state',Number(e.target.value))}>{['Habilitado','Deshabilitado','Auditoría'].map((x,i)=><option key={x} value={i}>{t(x)}</option>)}</select></label><label>{t('Peso')}<input type="number" min={-2147483647} max={2147483647} value={f.filter_weight} onChange={e=>change('filter_weight',Number(e.target.value))}/></label><label>{t('Descripción')}<textarea maxLength={4000} value={f.description} onChange={e=>change('description',e.target.value)}/></label></div>
 <h3>{t('Severidades')}</h3><div className="catalog-checks">{['Clear','Indeterminate','Warning','Minor','Major','Critical'].map((label,i)=><label key={label}><input type="checkbox" checked={f.severities?.includes(i)||false} onChange={e=>{const values=e.target.checked?[...(f.severities||[]),i]:(f.severities||[]).filter(x=>x!==i);change('severities',values.length?values:null);}}/>{i} · {label}</label>)}<small>{t('Sin selección: todas las severidades')}</small></div>
 <h3>{t('Criterios')}</h3><p>{t('Todas las condiciones deben coincidir. Sin condiciones: todos los eventos del cliente y APPLID.')}</p>{Object.entries(f.criteria).map(([key,condition])=><div className="catalog-criterion" key={key}><strong>{key}</strong><select aria-label={t('Operador')+' '+key} value={condition.operator} onChange={e=>change('criteria',{...f.criteria,[key]:{operator:e.target.value,value:String(condition.value)}})}><option value="eq">{t('Igual')}</option><option value="eq_ci">{t('Igual sin mayúsculas')}</option><option value="regex_ci">Regex</option></select><select aria-label={t('Tipo de valor')+' '+key} disabled={condition.operator!=='eq'} value={typeof condition.value} onChange={e=>change('criteria',{...f.criteria,[key]:{...condition,value:e.target.value==='boolean'?false:e.target.value==='number'?0:String(condition.value)}})}><option value="string">{t('Texto')}</option><option value="number">{t('Número')}</option><option value="boolean">{t('Booleano')}</option></select>{typeof condition.value==='boolean'?<select aria-label={t('Valor')+' '+key} value={String(condition.value)} onChange={e=>change('criteria',{...f.criteria,[key]:{...condition,value:e.target.value==='true'}})}><option value="true">true</option><option value="false">false</option></select>:<input type={typeof condition.value==='number'?'number':'text'} step="any" aria-label={t('Valor')+' '+key} maxLength={512} value={String(condition.value)} onChange={e=>change('criteria',{...f.criteria,[key]:{...condition,value:typeof condition.value==='number'?Number(e.target.value):e.target.value}})}/>}<button type="button" aria-label={t('Quitar')+' '+key} onClick={()=>{const next={...f.criteria};delete next[key];change('criteria',next);}}>×</button></div>)}<select aria-label={t('Agregar criterio')} value="" onChange={e=>{if(e.target.value)change('criteria',{...f.criteria,[e.target.value]:{operator:'eq_ci',value:''}});}}><option value="">+ {t('Agregar criterio')}</option>{fields.filter(x=>!(x in f.criteria)).map(x=><option key={x}>{x}</option>)}</select>
 <h3>{t('Destinos y dependencias')}</h3><div className="catalog-destinations">{destinations.map(([id,label])=>{const target=f.targets.find(x=>x.target===id);return <div className="catalog-destination" key={id}><label className="catalog-switch"><input type="checkbox" checked={!!target} onChange={e=>enableTarget(id,e.target.checked)}/>{t('Lleva')} {label}</label>{target&&<><label>{t(id==='extensions'?'Referencia de extensión':id==='chatops'?'Teams de ChatOps':'Grupo asignado')}<input required={target.behavior!=='force_off'} maxLength={200} value={(id==='extensions'?target.actionReference:target.assignmentGroup)||''} onChange={e=>patchTarget(id,{[id==='extensions'?'actionReference':'assignmentGroup']:e.target.value})}/></label><label>{t('Comportamiento')}<select value={target.behavior} onChange={e=>patchTarget(id,{behavior:e.target.value})}><option value="enable">{t('Habilitado')}</option><option value="force_off">{t('Forzar apagado')}</option><option value="overlay">Overlay</option></select></label>{['gnm','cacf','chatops'].includes(id)&&<label className="catalog-switch"><input type="checkbox" checked={target.dependsOnTicketing} onChange={e=>patchTarget(id,{dependsOnTicketing:e.target.checked})}/>{t('Esperar al ticket')}</label>}<label>{t('Demora en segundos')}<input type="number" min={0} max={2147483647} value={target.delaySeconds??''} onChange={e=>patchTarget(id,{delaySeconds:e.target.value===''?null:Number(e.target.value)})}/></label></>}</div>;})}</div></>:<><div className="catalog-grid">{Object.entries(customerLabels).map(([key,label])=><label key={key}>{t(label)}<input required={['customer','customer_code','timezone'].includes(key)} disabled={key==='customer_code'&&!!c.updated_at} maxLength={key==='customer_code'?100:200} value={String(c[key as keyof Customer]??'')} onChange={e=>change(key,e.target.value)}/></label>)}</div><label className="catalog-switch"><input type="checkbox" checked={c.enabled} onChange={e=>change('enabled',e.target.checked)}/>{t('Habilitado')}</label><p>{t('Los grupos del cliente se sugieren al agregar un destino a un filtro. Los filtros existentes conservan su configuración.')}</p></>}
 </fieldset><footer>{draft.updated_at&&<button type="button" className="catalog-danger" disabled={busy} onClick={()=>setDeleting(!deleting)}>{t('Eliminar')}</button>}<span/ ><button type="button" disabled={busy} onClick={()=>setDraft(null)}>{t('Cancelar')}</button><button className="catalog-primary" disabled={busy||deleting}>{t(busy?'Guardando…':'Guardar')}</button></footer>{deleting&&<div className="catalog-error"><p>{t('Se eliminará este registro de PostgreSQL. Esta acción no se puede deshacer.')}</p><button type="button" disabled={busy} onClick={()=>void remove()}>{t('Confirmar eliminación')}</button></div>}</form>}</dialog>
 </section>;
}
