import {useEffect,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {api,ApiError,operation,type Operation} from '../blackouts/blackouts.api';
import {History} from '../blackouts/BlackoutsPage';
import {InventoryError} from '../inventory/InventoryPage';
import {ConditionEditor} from '../policy/ConditionEditor';
import {newRouting,validateRouting,supported,type Routing,type Registry,type Mixed} from './routing.model';
export function RoutingEditor({tenant,id,locked,conflict,onDraft,execute,reconcile,groups}:{groups:Mixed[];tenant:string;id:string;locked:boolean;conflict:boolean;onDraft:(r:Routing|null)=>void;execute:(o:Operation)=>Promise<void>;reconcile:()=>void}){
 const {t}=useI18n();const [rule,setRouting]=useState<Routing>(newRouting),[record,setRecord]=useState<Registry>(),[etag,setEtag]=useState('"0"'),[loading,setLoading]=useState(!!id),[error,setError]=useState<unknown>(),[reason,setReason]=useState(''),[confirmation,setConfirmation]=useState<Operation|null>(null),[valid,setValid]=useState(false),[validating,setValidating]=useState(false),[active,setActive]=useState<Routing>();
 useEffect(()=>{if(!id)return;const abort=new AbortController();api<Registry>(tenant,'/rules/'+encodeURIComponent(id),undefined,undefined,abort.signal).then(({data,etag})=>{if(abort.signal.aborted)return;if(data.rule.type!=='ROUTING'||!etag)throw new ApiError(422,'WRONG_RULE_TYPE');setRecord(data);setEtag(etag);setRouting({...data.rule,version:data.latestVersion+1});}).catch(e=>{if(!abort.signal.aborted)setError(e);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[tenant,id]);
 useEffect(()=>{onDraft(loading||id&&!record||!supported(rule)?null:rule);return()=>onDraft(null);},[rule,loading,id,record,onDraft]);
 const blocked=locked||loading||!!id&&!record||conflict||record?.status==='RETIRED'||!supported(rule)||!!confirmation||validating;
 function change(r:Routing){setRouting(r);setValid(false);setError(undefined);}
 async function check(){setValidating(true);setError(undefined);try{await api(tenant,'/rules/validate',{rule:validateRouting(rule)});setValid(true);}catch(e){setError(e);}finally{setValidating(false);}}
 function prepare(action:string){try{setError(undefined);if(!reason.trim()||reason.length>2048)throw new Error('Motivo de cambio obligatorio, máximo 2048 caracteres.');const path=action==='save'?'/rules':'/rules/'+encodeURIComponent(id)+'/'+action;setConfirmation(operation(tenant,path,action==='save'?{rule:validateRouting(rule),reason}:{version:action==='enable'?record!.latestVersion:record!.activeVersion??record!.latestVersion,reason},etag,rule.id));}catch(e){setError(e);}}
 return <article className="blackout-editor"><h2>{t('Ruta')} · {id||t('Nuevo')}</h2><InventoryError error={error}/>{record&&<p>{t('Estado')}: {record.status} · {t('Versión activa')}: {record.activeVersion??'—'} · {t('Última guardada')}: {record.latestVersion} · ETag {etag}</p>}{id&&<button disabled={locked||!!confirmation} onClick={reconcile}>{t('Cargar revisión actual y descartar borrador')}</button>}{conflict&&<p role="alert">{t('Tu borrador se conserva. Carga la revisión actual antes de preparar otra operación.')}</p>}{record?.activeVersion&&<button onClick={async()=>{try{const {data}=await api<Registry>(tenant,'/rules/'+encodeURIComponent(id)+'?version='+record.activeVersion);setActive(data.rule);}catch(e){setError(e);}}}>{t('Consultar definición activa')}</button>}{active&&<details open><summary>{t('Definición activa')}</summary><pre>{JSON.stringify(active,null,2)}</pre></details>}
 {!supported(rule)&&<><p role="status">{t('Perfil avanzado o Lifecycle: solo consulta, sin edición simplificada.')}</p><pre>{JSON.stringify(record?.rule??rule,null,2)}</pre></>}<fieldset disabled={blocked}><legend>{t('Nueva versión de la definición')}</legend><div className="blackout-fields"><label>ID<input aria-label="Routing ID" disabled={!!id} value={rule.id} onChange={e=>change({...rule,id:e.target.value})}/></label><label>{t('Prioridad')}<input type="number" value={rule.priority} onChange={e=>change({...rule,priority:Number(e.target.value)})}/></label><label>{t('Responsable')}<input value={rule.metadata.owner} onChange={e=>change({...rule,metadata:{...rule.metadata,owner:e.target.value}})}/></label><label>{t('Descripción')}<textarea value={rule.metadata.description??''} onChange={e=>change({...rule,metadata:{...rule.metadata,description:e.target.value}})}/></label><label>{t('Etiquetas, una por línea')}<textarea value={rule.metadata.tags?.join('\n')??''} onChange={e=>change({...rule,metadata:{...rule.metadata,tags:e.target.value.split('\n').filter(Boolean)}})}/></label></div>
 <ConditionEditor value={rule.condition} onChange={condition=>change({...rule,condition})}/><h3>CREATE_TICKET · {rule.actions[0]?.target} · default</h3><label>{t('Proveedor')}<select value={rule.actions[0]?.target??'SERVICENOW'} onChange={e=>change({...rule,actions:[{...rule.actions[0],target:e.target.value}]})}><option value="SERVICENOW">ServiceNow</option><option value="GLPI">GLPI</option></select></label><label>{t('Regla de correlación')}<select aria-label={t('Regla de correlación')} value={String(rule.actions[0]?.parameters?.correlationRuleId??'')} onChange={e=>change({...rule,actions:[{...rule.actions[0],parameters:{...rule.actions[0].parameters,correlationRuleId:e.target.value}}]})}><option value="">{t('Seleccionar')}</option>{!groups.some(g=>g.id===rule.actions[0]?.parameters?.correlationRuleId)&&!!rule.actions[0]?.parameters?.correlationRuleId&&<option value={String(rule.actions[0].parameters.correlationRuleId)}>{String(rule.actions[0].parameters.correlationRuleId)} · {t('No encontrada')}</option>}{groups.map(g=><option key={g.id} value={g.id}>{g.id} · {g.status} · {t('Versión activa')}: {g.activeVersion??'—'} · {t('Última guardada')}: {g.latestVersion}</option>)}</select></label><p>{t('La referencia no garantiza existencia ni grupo activo aplicable. Compruébala mediante simulación.')}</p>
 <label className="inventory-check"><input type="checkbox" checked={rule.enabled} onChange={e=>change({...rule,enabled:e.target.checked})}/>{t('Versión habilitable (no activa al guardar)')}</label><button onClick={check}>{t('Validar definición')}</button>
 </fieldset>

 {valid&&<p role="status">{t('Definición válida. Aún no está guardada.')}</p>}<fieldset disabled={blocked}><legend>{t('Operaciones de la configuración')}</legend><label>{t('Motivo del cambio')}<textarea value={reason} maxLength={2048} onChange={e=>setReason(e.target.value)}/></label><div className="blackout-actions"><button onClick={()=>prepare('save')}>{t('Guardar nueva versión')}</button>{record&&<><button disabled={!record.rule.enabled} onClick={()=>prepare('enable')}>{t('Activar última guardada')}</button><button onClick={()=>prepare('disable')}>{t('Desactivar')}</button><button onClick={()=>prepare('retire')}>{t('Retirar')}</button></>}</div></fieldset>{record?.status==='RETIRED'&&<p>{t('Retirado: estado terminal. El historial se conserva.')}</p>}
 {confirmation&&<section className="blackout-confirm" aria-label={t('Confirmar operación')}><h3>{t('Confirmar operación')}</h3><p>Tenant: {tenant} · ID: {rule.id} · If-Match: {etag}</p><p>{t(confirmation.path==='/rules'?'Guardar no activa. La versión activa anterior seguirá ejecutándose.':confirmation.path.endsWith('/retire')?'Retirar es terminal y bloquea la reactivación.':'Esta operación cambia el estado operativo de la regla guardada.')}</p>{confirmation.path.endsWith('/disable')&&<p>{t('Desactivar detiene la evaluación de esta ruta.')}</p>}<pre>{confirmation.body}</pre><button disabled={locked} onClick={()=>{const op=confirmation;setConfirmation(null);void execute(op);}}>{t('Confirmar envío')}</button><button disabled={locked} onClick={()=>setConfirmation(null)}>{t('Cancelar')}</button></section>}{record&&<History tenant={tenant} id={id}/>}</article>;
}
