import {validateCondition,type Condition} from '../policy/policy.model';
import type {Summary} from '../correlation/correlation.model';
export type Routing={id:string;version:number;type:'ROUTING';enabled:boolean;priority:number;condition:Condition;actions:{type:string;target:string;parameters:Record<string,unknown>}[];metadata:{owner:string;description?:string;tags?:string[]}};
export type AnyRule={id:string;version:number;enabled:boolean;type?:string;strategy?:string;[key:string]:unknown};
export type Registry=Summary&{rule:Routing;checksum:string};
export type Mixed=Summary&{rule:AnyRule;checksum:string};
export const newRouting=():Routing=>({id:'',version:1,type:'ROUTING',enabled:true,priority:10,condition:{field:'event.severity',operator:'GTE',value:2},actions:[{type:'CREATE_TICKET',target:'SERVICENOW',parameters:{configuration:'default',correlationRuleId:''}}],metadata:{owner:'operations'}});
export function supported(r:Routing){return r.type==='ROUTING'&&Array.isArray(r.actions)&&r.actions.length===1&&r.actions.every(a=>a.type==='CREATE_TICKET'&&['SERVICENOW','GLPI'].includes(a.target??'')&&a.parameters?.configuration==='default'&&typeof a.parameters.correlationRuleId==='string'&&Object.keys(a).every(k=>['type','target','parameters'].includes(k))&&Object.keys(a.parameters).every(k=>['configuration','correlationRuleId'].includes(k)));}
export function validateRouting(r:Routing){if(!supported(r))throw new Error('Perfil avanzado o Lifecycle: solo consulta, sin edición simplificada.');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(r.id)||!Number.isSafeInteger(r.version)||r.version<1)throw new Error('ID o versión de ruta inválido.');if(!Number.isSafeInteger(r.priority)||!r.metadata.owner.trim())throw new Error('Completa responsable y prioridad entera.');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(String(r.actions[0].parameters.correlationRuleId)))throw new Error('Selecciona una regla de correlación.');validateCondition(r.condition);return r;}
