import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {api} from '../blackouts/blackouts.api';
import {InventoryError} from '../inventory/InventoryPage';
import {eventsFor,type SequenceRow} from '../correlation/correlation.model';
import {validateRouting,type Routing,type Mixed} from './routing.model';
type Decision={ruleId:string;ruleVersion:number;correlationRuleId:string;reason:string;commandId?:string};
type Result={candidates?:unknown[];routing?:{decisions?:Decision[];commands?:unknown[]};results?:Result[];[key:string]:unknown};
const example=():SequenceRow[]=>['OPEN','OPEN','CLOSE'].map((action,i)=>({key:i===1?'member-b':'member-a',node:'router-1',action:action as 'OPEN'|'CLOSE',at:new Date(Date.now()+i*1000).toISOString()}));
export function RoutingSimulation({tenant,draft,revision,records,complete}:{tenant:string;draft:Routing|null;revision:number;records:Mixed[];complete:boolean}){
 const {t}=useI18n();const [rows,setRows]=useState(example),[candidate,setCandidate]=useState(false),[selected,setSelected]=useState<string[]>([]),[includeDraft,setIncludeDraft]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[result,setResult]=useState<Result>(),[submitted,setSubmitted]=useState<{revision:number;mode:string}>(),[id,setId]=useState(''),[explain,setExplain]=useState<Result>(),[explainError,setExplainError]=useState<unknown>(),[explaining,setExplaining]=useState(false);const request=useRef<AbortController>();useEffect(()=>()=>request.current?.abort(),[]);
 async function simulate(){if(request.current)return;const abort=new AbortController();request.current=abort;setBusy(true);setError(undefined);setResult(undefined);try{const candidates=new Map<string,unknown>(records.filter(r=>selected.includes(r.id)).map(r=>[r.id,r.rule]));if(candidate&&includeDraft){if(!draft)throw new Error('No hay un borrador disponible para esta simulación.');candidates.set(draft.id,validateRouting(draft));}if(candidate&&(!complete||!candidates.size||candidates.size>256))throw new Error('Selecciona de 1 a 256 definiciones candidatas.');const events=eventsFor(rows,tenant);const body={...(events.length===1?{event:events[0]}:{events}),...(candidate?{candidateRules:[...candidates.values()]}:{})};const {data}=await api<Result>(tenant,'/simulations',body,undefined,abort.signal);if(!abort.signal.aborted){setResult(data);setSubmitted({revision,mode:candidate?'CANDIDATE':'ACTIVE'});}}catch(e){if(!abort.signal.aborted)setError(e);}finally{if(!abort.signal.aborted)setBusy(false);request.current=undefined;}}
 function change(i:number,patch:Partial<SequenceRow>){setRows(a=>a.map((r,n)=>n===i?{...r,...patch}:r));}
 return <><article className="blackout-editor"><h2>{t('Simulación de Routing')}</h2><p>{t('Cada petición comienza con estado y ledger vacíos. No consulta producción ni envía al proveedor.')}</p><p>{t('Los comandos son intenciones inmutables, no tickets confirmados. No se pueden editar, borrar ni reenviar desde esta vista.')}</p><fieldset disabled={busy}><label className="inventory-check"><input type="checkbox" checked={candidate} onChange={e=>setCandidate(e.target.checked)}/>{t('Conjunto candidato')}</label>{candidate&&<><p>{t('La candidata reemplaza todo el snapshot: selecciona correlación y ruta, además de otras capacidades necesarias.')}</p>{records.map(r=><label className="inventory-check" key={r.id}><input type="checkbox" disabled={!complete} aria-label={`${t('Candidato')} ${r.id}`} checked={selected.includes(r.id)} onChange={e=>setSelected(a=>e.target.checked?[...a,r.id]:a.filter(x=>x!==r.id))}/>{r.id} · {r.rule.type??r.rule.strategy} · v{r.latestVersion} · {r.status} · enabled: {String(r.rule.enabled)}</label>)}<label className="inventory-check"><input type="checkbox" disabled={!draft} checked={includeDraft} onChange={e=>setIncludeDraft(e.target.checked)}/>{t('Incluir borrador abierto')}</label><p>{t('El borrador reemplaza la versión seleccionada del mismo ID. Cada escritura se confirma por separado.')}</p></>}
 <div className="catalog-table-wrap"><table><thead><tr>{['Miembro (eventKey)','Recurso','Acción','receivedAt ISO','Quitar'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><input aria-label={`eventKey ${i+1}`} value={r.key} onChange={e=>change(i,{key:e.target.value})}/></td><td><input aria-label={`resource ${i+1}`} value={r.node} onChange={e=>change(i,{node:e.target.value})}/></td><td><select aria-label={`action ${i+1}`} value={r.action} onChange={e=>change(i,{action:e.target.value as 'OPEN'|'CLOSE'})}><option>OPEN</option><option>CLOSE</option></select></td><td><input aria-label={`receivedAt ${i+1}`} value={r.at} onChange={e=>change(i,{at:e.target.value})}/></td><td><button aria-label={`${t('Quitar evento')} ${i+1}`} disabled={rows.length===1} onClick={()=>setRows(a=>a.filter((_,n)=>n!==i))}>−</button></td></tr>)}</tbody></table></div><p>{t('OPEN usa severidad 3; CLOSE usa 0. Los eventIds son únicos por envío. Usa tiempos crecientes y el mismo recurso para probar deduplicación.')}</p><button disabled={rows.length>=64} onClick={()=>setRows(a=>[...a,{key:'member-'+(a.length+1),node:'router-1',action:'OPEN',at:new Date(Date.parse(a[a.length-1].at)+1000).toISOString()}])}>{t('Agregar evento')}</button><button onClick={()=>setRows(example())}>{t('Cargar ejemplo de ciclo')}</button><button onClick={simulate}>{t('Simular secuencia')}</button></fieldset><InventoryError error={error}/>{result&&<section role="status"><p>{submitted?.mode} · Tenant: {tenant}</p>{submitted?.revision!==revision&&<p>{t('La configuración cambió desde esta consulta. Vuelve a simular para ver el estado actual.')}</p>}<Results result={result}/></section>}</article>
 <article className="blackout-editor"><h2>{t('Evidencia de evento real')}</h2><p>{t('La intención o publicación de un comando no prueba éxito del proveedor. Esta vista no consulta estados del Worker.')}</p><label>processingId<input value={id} onChange={e=>setId(e.target.value)}/></label><button disabled={explaining||!id.trim()} onClick={async()=>{setExplaining(true);setExplainError(undefined);setExplain(undefined);try{setExplain((await api<Result>(tenant,'/explain/'+encodeURIComponent(id.trim()))).data);}catch(e){setExplainError(e);}finally{setExplaining(false);}}}>{t('Consultar evidencia')}</button><InventoryError error={explainError}/>{explain&&<Results result={explain}/>}</article></>;
}
function Results({result}:{result:Result}){const {t}=useI18n();return <>{(result.results??[result]).map((r,i)=><section key={i}><h3>{t('Evento')} {i+1} · {t('Candidatos')}: {r.candidates?.length??0}</h3><div className="catalog-table-wrap"><table aria-label={`${t('Decisiones de Routing')} ${i+1}`}><thead><tr>{['ruleId','ruleVersion','correlationRuleId','reason','commandId'].map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{r.routing?.decisions?.map((d,n)=><tr key={n}>{(['ruleId','ruleVersion','correlationRuleId','reason','commandId'] as const).map(k=><td key={k}>{String(d[k]??'—')}</td>)}</tr>)}</tbody></table></div><details><summary>{t('Candidatos y comandos inmutables')}</summary><pre>{JSON.stringify({candidates:r.candidates,commands:r.routing?.commands},null,2)}</pre></details></section>)}<details><summary>{t('Respuesta completa')}</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>;}
