import {useEffect,useRef,useState} from 'react';
import {useI18n} from '../../shared/i18n/I18nProvider';
import {api,ApiError,type Operation} from '../blackouts/blackouts.api';
import {RoutingEditor} from './RoutingEditor';
import {InventoryError} from '../inventory/InventoryPage';
import {RoutingSimulation} from './RoutingSimulation';
import type {Routing, Mixed} from './routing.model';
import type {Summary} from '../correlation/correlation.model';
import '../catalog/catalog.css';import '../blackouts/blackouts.css';import '../inventory/inventory.css';
const storage='console.routing.pending';
function pendingOperation():Operation|null{try{return JSON.parse(sessionStorage.getItem(storage)||'null');}catch{return null;}}
export function RoutingPage(){
 const {t}=useI18n();const [pending,setPending]=useState(pendingOperation),[tenant,setTenant]=useState(()=>pendingOperation()?.tenant??''),[input,setInput]=useState(()=>pendingOperation()?.tenant??''),[rows,setRows]=useState<Mixed[]>([]),[progress,setProgress]=useState({pages:0,read:0}),[loading,setLoading]=useState(false),[readErrors,setReadErrors]=useState<string[]>([]),[query,setQuery]=useState(''),[revision,setRevision]=useState(0),[editorKey,setEditorKey]=useState(0),[selected,setSelected]=useState<string|null>(()=>pendingOperation()?.ruleId??null),[draft,setDraft]=useState<Routing|null>(null),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),[conflict,setConflict]=useState(false),[busy,setBusy]=useState(false);const lock=useRef(false);
 useEffect(()=>{const abort=new AbortController();setRows([]);setProgress({pages:0,read:0});setReadErrors([]);if(!tenant){setLoading(false);return;}setLoading(true);
  (async()=>{let cursor:string|number|undefined;let pages=0,read=0;const found:Mixed[]=[];const errors:string[]=[];const visited=new Set<string>();
   try{do{const {data}=await api<{items:Summary[];next:string|number|null}>(tenant,'/rules?limit=50'+(cursor===undefined?'':'&after='+encodeURIComponent(cursor)),undefined,undefined,abort.signal);if(abort.signal.aborted)return;
    if(!Array.isArray(data.items))throw new ApiError(503,'INVALID_RESPONSE');
    for(let start=0;start<data.items.length;start+=4){await Promise.all(data.items.slice(start,start+4).map(async item=>{try{const {data:record}=await api<Mixed>(tenant,'/rules/'+encodeURIComponent(item.id),undefined,undefined,abort.signal);found.push(record);}catch(e){if(!abort.signal.aborted)errors.push(`${item.id}: ${e instanceof ApiError?'HTTP '+e.status+' · '+e.code:String(e)}`);}finally{read++;}}));if(abort.signal.aborted)return;setRows([...found]);setReadErrors([...errors]);setProgress({pages:pages+1,read});}
    pages++;cursor=data.next??undefined;if(cursor!==undefined){if(visited.has(String(cursor)))throw new ApiError(503,'REPEATED_CURSOR');visited.add(String(cursor));}
   }while(cursor!==undefined&&!abort.signal.aborted);
   }catch(e){if(!abort.signal.aborted)setReadErrors([...errors,e instanceof ApiError?'HTTP '+e.status+' · '+e.code:String(e)]);}finally{if(!abort.signal.aborted){setLoading(false);setProgress({pages,read});}}
  })();return()=>abort.abort();
 },[tenant,revision]);
 async function execute(op:Operation){if(lock.current)return;lock.current=true;setBusy(true);setError(undefined);setNotice('');try{sessionStorage.setItem(storage,JSON.stringify(op));setPending(op);await api(op.tenant,op.path,JSON.parse(op.body),op);sessionStorage.removeItem(storage);setPending(null);setSelected(op.ruleId);setConflict(false);setEditorKey(x=>x+1);setRevision(x=>x+1);setNotice(op.path==='/rules'?'Guardado, pendiente de activación. La versión activa anterior se conserva.':'Cambio confirmado por el servidor.');}catch(e){setError(e);if(op.path.endsWith('/enable'))setNotice('Versión guardada; activación pendiente de confirmar.');if(e instanceof ApiError&&[400,404,409,413,422,428].includes(e.status)){sessionStorage.removeItem(storage);setPending(null);if(e.status===409){setConflict(true);setRevision(x=>x+1);}}}finally{lock.current=false;setBusy(false);}}
 const locked=busy||!!pending;
 return <section className="page catalog-page blackout-page"><div className="page-heading"><div><span className="eyebrow">Event Processor</span><h1>{t('Routing y comandos')}</h1><p>{t('Rutas base y resultados inmutables del motor.')}</p></div><button disabled={locked||loading||!tenant} onClick={()=>setRevision(x=>x+1)}>{t('Actualizar tabla')}</button></div>
 <div className="catalog-toolbar"><label>Tenant<input aria-label="Tenant" disabled={locked} value={input} onChange={e=>setInput(e.target.value)}/></label><button disabled={locked} onClick={()=>{setTenant(input.trim());setSelected(null);setDraft(null);setError(undefined);setConflict(false);setNotice('');}}>{t('Seleccionar tenant')}</button><input aria-label={t('Buscar en la tabla')} value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={!tenant||locked} onClick={()=>{setSelected('');setEditorKey(x=>x+1);setConflict(false);setNotice('');}}>{t('Nueva ruta')}</button></div>
 <p>{tenant?`${t('Tenant seleccionado')}: ${tenant}`:t('Selecciona un tenant para consultar, escribir o simular.')}</p><p>{t('Guardar no activa ni reprocesa eventos históricos. Una intención de comando no acredita éxito remoto.')}</p>
 <InventoryError error={error}/>{notice&&<p role="status" className="blackout-notice">{t(notice)}</p>}{pending&&<div role="status"><p>{t('Operación pendiente de confirmar. Reintenta exactamente la misma solicitud antes de realizar otro cambio.')}</p><code>{pending.key}</code><button disabled={busy} onClick={()=>execute(pending)}>{t('Reintentar misma operación')}</button></div>}
 {tenant&&<><p role="status">{t(loading?'Leyendo definiciones…':'Lectura finalizada')} · {t('Páginas')}: {progress.pages} · {t('Definiciones')}: {progress.read}</p>{readErrors.length>0&&<div role="alert"><strong>{t('Listado incompleto: corrige los errores y actualiza.')}</strong>{readErrors.map((e,i)=><p key={i}>{e}</p>)}</div>}<div className="catalog-table-wrap"><table><thead><tr>{['ID','Estado','Versión activa','Última guardada','Perfil','Detalle'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{rows.filter(r=>r.rule.type==='ROUTING').filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.id}><td>{r.id}</td><td>{r.status}</td><td>{r.activeVersion??'—'}</td><td>{r.latestVersion}</td><td>{t('ROUTING')}</td><td><button aria-label={`${t('Abrir regla')} ${r.id}`} disabled={locked} onClick={()=>{setSelected(r.id);setEditorKey(x=>x+1);setConflict(false);setNotice('');}}>{t('Abrir')}</button></td></tr>)}</tbody></table></div>{!loading&&!rows.length&&!readErrors.length&&<p>{t('Sin registros')}</p>}</>}
 {tenant&&selected!==null&&<RoutingEditor groups={rows.filter(r=>!!r.rule.strategy)} key={tenant+':'+selected+':'+editorKey} tenant={tenant} id={selected} locked={locked} conflict={conflict} onDraft={setDraft} execute={execute} reconcile={()=>{setConflict(false);setError(undefined);setEditorKey(x=>x+1);setRevision(x=>x+1);}}/>}
 {tenant&&<RoutingSimulation key={tenant} tenant={tenant} draft={draft} revision={revision} records={rows} complete={!loading&&!readErrors.length}/>}
 </section>;
}
